### ISSUE TITLE
OpenSlide Error with Pixman Version 0.38 (Ubuntu 20.x)

### ISSUE THREAD

**Issue by John-P** [TissueImageAnalytics/tiatoolbox#133]
* TIA Toolbox version: Any
* Python version: Any
* Operating System: Ubuntu 20.x

### Description

When using OpenSlide on Ubuntu 20.x versions, the included libpixman library version (0.38) causes errors which reading any pyramid level other than 0. See issue https://github.com/openslide/openslide-python/issues/114 and https://github.com/openslide/openslide/issues/291 for more. Using conda this can easily be fixed by installing another version (our requirements files use the correct version). However if installing from pip and using apt for packages such as openslide and openjpeg then this will be an issue as apt will not (without a lot of fussing) allow installing another version.

* Ubuntu versions of pixman: https://packages.ubuntu.com/search?keywords=libpixman-1-0

### Proposed Mitigation

Add a check on import of OpenSlideReader to check if the system is GNU Linux and pixman version 0.38 is being used. If so, display a warning to the user. The user may have to use conda or install a different pixman version from source.

**Comment by mostafajahanifar** [comment]
Currently I'm using the following Linux distribution:
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
```
Which has `libpixman` version 0.38.4 installed. I'm running into the same issue reported here. Here is an example code for extracting slide overview:
```
wsi = wsireader.WSIReader.open(file)
overview = wsi.slide_thumbnail(resolution=4, units='level')
cv2.imwrite('save_path.png', overview[:,:,::-1])
```
the result looks like this:
![1M001_lr](https://user-images.githubusercontent.com/74412979/143030822-83066a4d-991a-4c1a-af2d-d7367feaa0d5.png)

I also tried extracting some patches, results
![1005](https://user-images.githubusercontent.com/74412979/143030932-e881ca44-24bf-4faf-974d-50c8b9780e31.jpg)
:
![970](https://user-images.githubusercontent.com/74412979/143030951-c0659345-fbeb-4a4e-b095-887de3ee4d42.jpg)

**Comment by mostafajahanifar** [comment]
[Fixing the problem in Linux Ubuntu 20.04.3]

There are several solutions reported to solve this problem. For example:
1) if you are using Conda environments, you can easily call the following command to install the right version of the `pixman` library:
`conda install -c conda-forge pixman`
this will install the latest version of the `pixman` lib (0.4.0) which has this bug resolved.
2) Some of the Linux distributions officially support other versions of the the `pixman` library. Check the following link to see if you can install one of the working versions (0.34, 0.36, 0.40) on your Linux distribution using `apt-get install` command.
3) For the worst case scenario (no conda and Ubuntu version 20.04.3 for example) you can build the `pixman` lib from the source. It doesn't have any particular dependency so it's easy to build manually. Follow the instruction here: https://www.linuxfromscratch.org/blfs/view/svn/general/pixman.html, you only need to install `pip install meson, ninja` beforehand.
