### ISSUE TITLE
Deprecate "power" and move to "appmap"

### ISSUE THREAD

**Issue by John-P** [TissueImageAnalytics/tiatoolbox#149]
* TIA Toolbox version: <=0.7.0
* Python version: any
* Operating System: any

### Description

I would like to suggest changing the WSIReader option currently called "power" to "appmag" (or similar). The word "power" was a carry over from the openslide metadata referring to "objective power". However, this is (in most cases) actually referring to the total apparent magnification not the power of the objective lens alone. This small change would avoid confusion. We could keep "power" functioning as an alias with a deprecation notice at least until version 1.0 for backward compatibility.

**Comment by DavidBAEpstein** [comment]
@shaneahmed @simongraham @vqdang @John-P 
Is the terminology used in tiatoolbox standard in the pathology community? Before we make any change such as John suggests, we should find out from pathologists (from more than one pathologist) what terminology they use. To see one view Google "A level notes magnification resolution" and look at the top hit. You can also look at  https://courses.lumenlearning.com/ap1x94x1/chapter/magnification-and-resolution/
But neither of these are for an audience of pathologists. For that audience, look at 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3779393/
which is a scientific article trying to clarify issues (of the meaning of words) that arise when pathologists first meet digital pathology. You will see that there are many opportunities for confusion.

I think we should have a discussion with pathologists to make sure what words the pathology community uses and with what meaning, before undertaking a change in documentation that is likely to affect many files. If there are to be such changes, I would like to be sure that they are in line with the expectations of pathologists and are not open to misinterpretation by them.

**Comment by John-P** [comment]
Yes a look into the manufacturer language is a good idea. I know that both Aperio (SVS) and Omnyx (JP2) use "AppMag" in their metadata. However, it is Python convention to use lowercase is string options i.e.g "appmag". I will have a look into some other sources to provide a more comprehensive list.

**Comment by shaneahmed** [comment]
We will keep the current setting for "objective_power" to avoid inconsistency across different versions.
