### ISSUE TITLE
Method not supported

### ISSUE THREAD

**Issue by engrodawood** [TissueImageAnalytics/tiatoolbox#164]
* TIA Toolbox version: 0.7
* Python version: 3.8
* Operating System: Linux

### Description

Extracting patches with there x and y coordinates 

### What I Did

```
patch_extractor = patchextraction.get_patch_extractor(
            input_img=wsi, # input image path, numpy array, or WSI object
            method_name="slidingwindow", 
            patch_size=(256, 256), # size of the patch to extract around the centroids from centroids_list
            stride=(256, 256)) 
```
MethodNotSupported: Method is not supported

**Comment by shaneahmed** [comment]
This has been fixed in v 0.8.0

Please try 

`fixed_patch_extractor = patchextraction.get_patch_extractor(
        input_img=wsi, # input image path, numpy array, or WSI object
        method_name="slidingwindow", # also supports "point" and "slidingwindow"
        patch_size=(256, 256), # size of the patch to extract around the centroids from centroids_list
        stride=(256, 256) # stride of extracting patches, default is equal to patch_size
    )`
