### ISSUE TITLE
Incorrect mask-based patch extraction

### ISSUE THREAD

**Issue by mostafajahanifar** [TissueImageAnalytics/tiatoolbox#199]
* TIA Toolbox version: 0.8.0@develop
* Python version: 3.8.10
* Operating System: Ubuntu 20.04.3

### Description

During the the mask-based patch extraction, I realized that the default coordinate selection helper function (`default_sel_func`) in the `    filter_coordinates` method does not work as expected. The reason is that for each input coordination, `default_sel_func` uses `read_bounds` method of mask's VirtualWSI to extract the corresponding region of the input coordination. However, during the the `read_bounds` call, `resolution` and `unit` arguments are provided and also `coord_space` is set to `"resolution"`:
https://github.com/TissueImageAnalytics/tiatoolbox/blob/866c6038452f9adbdc30a2fb3ea55adcab046873/tiatoolbox/tools/patchextraction.py#L242

Now, because `coord` input is coordination that is already converted to the `'baseline'` resolution, `read_bounds` method will extract regions according to the baseline `coords` but from the user's selected `resolution` and `unit` (which are set during the initialization of the patchextractor) and this will result to wrong mask's patch extraction. Note that this won't be an issue if user wants to extract patches at level 0 (or baseline resolution), the problem only raises if user wants to extracted patches at higher levels.

### Potential Solutions
1) We can simply remove all the argument's from `read_bounds` method's input, except for `coord`. This way, `read_bounds` will use `coord_space='baseline'` as expected.
```
roi = reader.read_bounds(coord)
```
2) Rewrite the mask's patch extraction at  using `read_rect` method (similar to patch extraction from the original image in `__getitem__` method (if it's more efficient way to extract patches at various resolution):
https://github.com/TissueImageAnalytics/tiatoolbox/blob/866c6038452f9adbdc30a2fb3ea55adcab046873/tiatoolbox/tools/patchextraction.py#L143.

**Comment by shaneahmed** [comment]
Resolved in this commit https://github.com/TissueImageAnalytics/tiatoolbox/commit/9bb597d7335925a4efee7d1968a6d554f3eab035
