### ISSUE TITLE
APIs break when slide metadata is missing

### ISSUE THREAD

**Issue by ralfbanisch** [TissueImageAnalytics/tiatoolbox#203]
* TIA Toolbox version: 0.8.0@develop
* Python version: 3.8.5
* Operating System: ubuntu 20.04

### Description

Many of the TIA toolbox APIs silently assume complete slide metadata, e.g. `mpp` and `power`. However, some slides may have incomplete metadata (I myself work with slides that don't have `mpp` and `power` metadata), and that will break many of the APIs, e.g. there are places in the code where some mask is created and the unit "power" is hardcoded - this will fail if metadata is missing and the user has no way to recover from it.

Since the `level` coordinate units are always going to be there, it would be good if there was a way to use all APIs with this coordinate system, perhaps even as default.

**Comment by John-P** [comment]
Hi @ralfbanisch, I'd like to look into improving this. Could you possibly specify which functions are breaking for you or provide a small code snippet example? I can see there may be issues with patch prediction and semantic segmentation if this metadata is missing. Is there something else that is breaking for you?
