### ISSUE TITLE
Patch Predictor creating output on standard error not standard out

### ISSUE THREAD

**Issue by johne131** [TissueImageAnalytics/tiatoolbox#255]
* TIA Toolbox version: 1.0.0
* Python version: 3.8
* Operating System: Ubuntu 20.04

### Description

This command:
The output is on standard error not standard out.

### What I Did
Using LSF by running:

docker run --rm --name tiatoolbox_gpu_test.sh_bioformatspull2759.ndpi -v $v1 --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES="7" tialab/tiatoolbox_100_py39_cuda:t3 tiatoolbox patch-predictor --img-input /root/workspace/tiatoolbox_sample_wsis/bioformatspull2759.ndpi --mode wsi --on-gpu True --output-path /root/workspace/segment-results_bioformatspull2759.ndpi

The output appears in the LSF [job number].err file and not in [job number].out

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by John-P** [comment]
@shaneahmed @vqdang I see there is a linked merged PR here. Is this issue solved now?
