### ISSUE TITLE
Issue when using WSIReader.open() for .tif images

### ISSUE THREAD

**Issue by GzrDavidRicardo** [TissueImageAnalytics/tiatoolbox#256]
* TIA Toolbox version:  1.0.0
* Python version: 3.9.9
* Operating System: Ubuntu 20.04

### Description

I was trying to use WSIReader.open() to read .tif images downloaded from Camelyon16 dataset and the codes are as follows:

> import requests
> from tiatoolbox.wsicore.wsireader import WSIReader, get_wsireader
> import os
> import numpy as np
> import matplotlib.pyplot as plt
> import matplotlib as mpl
> 
> mpl.rcParams['figure.dpi'] = 150 # for high resolution figure in notebook
> 
> sample_wsi_path = '/home/gzr/code/NIC/data/CAMELYON16/training/normal/normal_001.tif'
> 
> wsi = WSIReader.open(input_img=sample_wsi_path)
> print(type(wsi))

And I'm sure the image path is correct, however, the following problem showed up:

> error: OpenCV(4.5.4) /tmp/pip-req-build-kv0l0wqx/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by shaneahmed** [comment]
You can try [OpenSlideWSIReader](https://tia-toolbox.readthedocs.io/en/latest/_autosummary/tiatoolbox.wsicore.wsireader.OpenSlideWSIReader.html)

**Comment by shaneahmed** [comment]
Closing this issue. Feel free to reopen if the above doesn't solve the problem.

**Comment by John-P** [comment]
One enhancement we could make to fix this issue is to check for tiles in the TIFF file. If it contains tiles, treat it as a WSI, else treat it as a normal image (tile / visual field).

**Comment by ds2268** [comment]
I have tried the above-mentioned solution for Camelyon16 slides and the same error persists.
