### ISSUE TITLE
Feature: Mask should support boundery padding as well

### ISSUE THREAD

**Issue by ds2268** [TissueImageAnalytics/tiatoolbox#259]
Hi,

often you might have labels only in some region of the slide (e.g. all cells labeled in some ROI) and you provide a mask (e.g. out of ROI polygon) to extract patches only from that region, but when you use within_bound=False, patches are extracted out of boundary as well (as expected and fine), but part of the patch should be also masked (i.e. have an option for that). Currently padding ON/OFF is only supported for out of WSI region. I would like to have this kind of support also for the inside "out of mask" region (e.g. part of border patches when within_bound=False will not have complete labels and the tissue should be masked with a constant value).

I see 2 options how to implement this:
- add mask as an argument to "read_rect" which should deal with that in the background
- besides returning the patch, return also "valid mask", which can be easily obtained out of "coords_list"

If you see the use of this and you provide some ideas what would be the best option to have this, I can implement it and make the PR. I have real-world use case on which I can try :)

**Comment by vqdang** [comment]
Hi, in case you want to have more fine-grain control. You can use this approach rather than using the provided patch from the PatchExtractor, then you can control what type of padding you want.

```python
from tiatoolbox.tools.patchextraction import \
    SlidingWindowPatchExtractor as Extractor
from tiatoolbox.wsicore.wsireader import VirtualWSIReader, get_wsireader

img_path = f'{root_dir}/imgs/{base_name}.thumb.png'
msk_path = f'{root_dir}/msks/{base_name}.png'
save_path = f'{SAVE_DIR}/{idx}'

img_reader = get_wsireader(img_path)
bounds = Extractor(
    img_reader,
    patch_size=patch_shape,
    stride=overlap_shape,
    within_bound=False,
    **resolution_kwargs
).coord_list

msk_reader = VirtualWSIReader(msk_path, mode='bool')
msk_reader.info = img_reader.info

for idx, bound in enumerate(bounds):
    img_patch = img_reader.read_bounds(
        bound,
        interpolation="optimise",
        coord_space='resolution',
        **resolution_kwargs,
    )
    msk_patch = msk_reader.read_bounds(
        bound,
        interpolation="nearest",
        coord_space='resolution',
        **resolution_kwargs,
    )

    base_name = f'{bound[0]:06d}-{bound[1]:06d}-{bound[2]:06d}-{bound[3]:06d}'
    imwrite(f'{save_path}.{base_name}.img.png', img_patch)
    imwrite(f'{save_path}.{base_name}.msk.png', msk_patch)
```

**Comment by shaneahmed** [comment]
Closing this issue. Feel free to reopen if you still see any problems with the above solution.
