### ISSUE TITLE
BUG: Need SQLite Version Requirement

### ISSUE THREAD

**Issue by vqdang** [TissueImageAnalytics/tiatoolbox#260]
* TIA Toolbox version: 1.0
* Python version: 3.7.7
* Operating System: Ubuntu 18.04

### Description

Annotation tests failled due to missing function in sqlite3.

![image](https://user-images.githubusercontent.com/24943262/149812981-e34f03fd-ae01-4c81-be25-1b19a2c22d92.png)

Sqlite version info of this runtime

![image](https://user-images.githubusercontent.com/24943262/149813052-7f0333ac-9a0c-44b1-8ae4-07ffd52eabf3.png)

### What I Did

```
Hatching Bugs
```

**Comment by John-P** [comment]
Thanks Dang. Looks like SQLite 3.35+ adds support for FLOOR. We could either fix this by making a custom function for lower SQLite version, or by simply showing a more helpful warning when trying to use FLOOR.
