### ISSUE TITLE
Add recipe for conda

### ISSUE THREAD

**Issue by sarthakpati** [TissueImageAnalytics/tiatoolbox#262]
* TIA Toolbox version: N.A.
* Python version: N.A.
* Operating System: N.A.

### Description

It would be great if this was available on conda in addition to pip.

### What I Did

N.A.

**Comment by sarthakpati** [comment]
I am happy to work on this.

**Comment by shaneahmed** [comment]
Thanks @sarthakpati It's on our to do list. 
One of the bottle necks is that openslide is not well supported on conda for Windows and breaks on some machines.
Any links or suggestions would be helpful.

**Comment by sarthakpati** [comment]
Actually, I can help you with that, as I have a baseline ready [[ref](https://github.com/conda-forge/staged-recipes/pull/17599)]. But, it fails because TIA requires opencv of a specific version, which conda doesn't have [[ref](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=444313&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=934)]. You can find all opencv versions available in conda [here](https://anaconda.org/conda-forge/opencv/files). Is there any way this dependency could be updated to `4.5.5`?

**Comment by shaneahmed** [comment]
sure, I can trigger a build with version `4.5.5` if it passes we are good to go.

**Comment by sarthakpati** [comment]
Just did: https://github.com/TissueImageAnalytics/tiatoolbox/pull/264 

😄

**Comment by shaneahmed** [comment]
> Just did: #264
> 
> 😄

Sorry I had created a branch and pushed the changes to all requirement files.

**Comment by shaneahmed** [comment]
@sarthakpati 
Opencv version and other libraries should be compatible now.

**Comment by sarthakpati** [comment]
Cool, are you pushing a new version to pip?

**Comment by shaneahmed** [comment]
Is this required?

**Comment by sarthakpati** [comment]
Unfortunately, yes, if we want to keep parity with future updates. Perhaps a small patch update to `1.0.1`?

**Comment by shaneahmed** [comment]
ok I will need to test all the example notebooks on develop before I make a release.

**Comment by sarthakpati** [comment]
Thanks!

**Comment by shaneahmed** [comment]
Release made https://github.com/TissueImageAnalytics/tiatoolbox/releases/tag/v1.0.1
Once it is on pypi https://pypi.org/project/tiatoolbox/ you can try again with the conda recipe

**Comment by shaneahmed** [comment]
v1.0.1 is up now on pypi https://pypi.org/project/tiatoolbox/1.0.1/

**Comment by sarthakpati** [comment]
Pull request is up on conda-forge: https://github.com/conda-forge/staged-recipes/pull/17599

**Comment by shaneahmed** [comment]
For windows cdeepakroy channel might be used for openslide binaries
https://anaconda.org/cdeepakroy/openslide-python

**Comment by sarthakpati** [comment]
Unfortunately, conda does not allow non-conda channels to be present in recipes (I think this is a security feature). In any case, perhaps openslide could be added a separate dependency for installation prior/after tia?

**Comment by shaneahmed** [comment]
TIAToolbox runs successfully on Windows via [WSL2 with CUDA support](https://docs.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl) so it should be alright.

**Comment by shaneahmed** [comment]
https://github.com/conda-forge/staged-recipes/pull/17599 is now merged. Feel free to reopen if there is any issue.

**Comment by sarthakpati** [comment]
I'll add a PR here with the conda recipe.
