### ISSUE TITLE
Clearing Away Debris In Jupyter Notebooks

### ISSUE THREAD

**Issue by DavidBAEpstein** [TissueImageAnalytics/tiatoolbox#324]
* TIA Toolbox version 1.0.1:
* Python version: 3.7.12
* Operating System: MacOS 11.6.4

### Description: **Cleaning up after a Jupyter notebook run**
I was trying to run one of our examples. Because of a coding error (not by me), the run came to a juddering halt with an error message. Afterwards, I noticed (but only because of using "git status") that a file had incorrectly been left behind, and would not be cleaned up for the next run.

To avoid problems, e notebook should begin each run with the same collection of unaltered files. Remember that these example notebooks will be run by a very large variety of users, some with very little experience.
### What I Did
Deleted the offending file and wrote this issue
### What should be done (in my opinion)
The right way to program the clean up is to create a special directory into which all downloaded or program-created files are placed. This is done correctly in the  first notebooks written for TIAToolbox (eg wsi-reading.ipynb).

At the beginning of the Jupyter notebook, delete that special directory and its contents. It is easy to leave debris lying around if this is not done. For example, the user may get bored and interrupt the execution, or there could be a very brief power cut or something else that you haven't thought of.

The existing Jupyter notebooks should be checked and improved where necessary.
```

**Comment by John-P** [comment]
The standard tempfile module may be of user here: https://docs.python.org/3/library/tempfile.html

**Comment by DavidBAEpstein** [comment]
examples/inference-pipelines/idars.ipynb has been fixed in PR #331, but I have not yet checked the other jupyter notebooks.
