### ISSUE TITLE
Read the Docs Rendering of Jupyter Notebook Markdown Cells is Incorrect

### ISSUE THREAD

**Issue by DavidBAEpstein** [TissueImageAnalytics/tiatoolbox#336]
### Description
Markdown cells in a jupyter notebook (JN) are processed in two different ways in our system. One is by JN markdown and the other is by sphinx for readthedocs. What looks great and makes sense in one, can look ugly and be meaningless in the other. Our JNs all look great in JN format, but the corresponding documentation in our readthecods can be meaningless and ugly. It is possible to fix some of these completely. For example, one can create a clickable "here" with the construct [here](url), which is rendered correctly in both contexts (though some characters, like "(" in the url component, need to be replaced by corresponding HTML code). But this compatible construct is not always used in our JNs, with resulting failure in readthedocs.

I do not know complete fixes for all incompatible constructs in our JNs, but there do seem to be kludges for all examples I've looked at, producing acceptable, though not perfect, results in both. At present readthedocs of our JNs is not acceptable, in my opinion. (It may be possible to fix these incompatibilities in a better way by a different configuration of sphinx or nbsphinx, but that is currently beyond my expertise. For example, can one alter docs/conf.py so that JN markdown  cells are rendered by JN markdown in readthedocs?)

This comment has been changing frequently as I have discovered more about the problem.

**Comment by John-P** [comment]
Perhaps it would be helpful to construct a document, in our wiki perhaps, detailing what does and does not work in both systems as a reference guide when writing these notebooks in future? I expect there is a lot of experimentation to find what works and it would be good ot keep track of the findings.

**Comment by John-P** [comment]
RE our last toolbox meeting, many of the notebooks log errors when running `make docs`. Perhaps we should have a PR to address these issues.

**Comment by John-P** [comment]
I believe this should be partly addressed by moving to myst parser for Sphinx. Now the docs (sphinx/read the docs) and Jupyter are using the same markdown parser and rendering should be more consistent.

**Comment by DavidBAEpstein** [comment]
This issue has been fixed by the introduction of appropriate pre-commit hooks.
