### ISSUE TITLE
Preprocessing pipeline and integration with hdf5?

### ISSUE THREAD

**Issue by omergra** [TissueImageAnalytics/tiatoolbox#348]
Hi everyone, 
Just started working with Tiatoolbox. 

First and foremost I need it for Tissue segmentation that will provide easy preprocessing, patching, mask saving, and reloading from a faster file format (e.g. hdf5). 

I am aware of the patch extraction module, and I understand it needs a mask as input. The thing is, that it seems the tissue mask module does not enable easy export of masks, nor for an easy preprocessing pipeline with validity checks on the masks that were received. 

1) Ability to export masks
2) Ability to validate tissue segmentation masks on large datasets
3) Patch extraction to a fast database format (hdf5) 

Are these functionalities existing and I simply didn't find them, or are they actually missing from the toolbox?

tnx

**Comment by shaneahmed** [comment]
We are working on using zarr/NGFF https://github.com/TissueImageAnalytics/tiatoolbox/pull/340

**Comment by shaneahmed** [comment]
- We do not have any plans to support HDF5. We would suggest to use NGFF/Zarr format which is supported in v1.2.0.
- Ability to export masks is already demonstrated in 03-tissue-masking example notebook.
