### ISSUE TITLE
Incorrect requirements.dev.conda.yml

### ISSUE THREAD

**Issue by DavidBAEpstein** [TissueImageAnalytics/tiatoolbox#352]
* TIA Toolbox version: 1.0.1
* However "tiatoolbox --version" also gives a warning message (see file)
* Python version: 3.8.13
* Operating System: Darwin Macos 11.6.6

1. conda env create --file requirements.dev.conda.yml catching error output in dev.err and standard output in dev.out
2. edit dev.err and dev.out to show what is going on, always appending.
3. minimal edit of requirements file to try to improve results
4. go to step 1 
5. Eventually succeeded, but still cannot be sure my tiatoolbox-dev environment is correct and will cope with running all the files in the toolbox.

[dev.err.txt](https://github.com/TissueImageAnalytics/tiatoolbox/files/8793780/dev.err.txt)
[dev.out.txt](https://github.com/TissueImageAnalytics/tiatoolbox/files/8793781/dev.out.txt)

**Comment by shaneahmed** [comment]
Issue related to failed `albumentations` conda build https://github.com/conda-forge/albumentations-feedstock

**Comment by DavidBAEpstein** [comment]
Fixed by @shaneahmed
