### ISSUE TITLE
Colab bug in master version of idars.ipynb

### ISSUE THREAD

**Issue by DavidBAEpstein** [TissueImageAnalytics/tiatoolbox#355]
* TIA Toolbox version: 1.1.0 (as reported by Colab--see file w* attached.
* Python version: 3.7.13 (as reported by Colab).
* Operating System: Colab's uname says "Linux"

### Description
I was trying to find out why my version of idars.ipynb kept crashing, no matter what I tried.
### What I Did
Checked masters version idars.ipynb on Colab. Two different ways of getting to Colab. First, git checkout master, upload idars.ipynb to Google Drive. Click to run it in Colab, Second run local version and click on Colab badge.
_Tell us what happened, what went wrong, and what you expected to happen._
1. Edit to change first mention of ON_GPU to ON_GPU=True
2. Check "runtime type" on Colab to make sure jnb runs with GPU enabled.
3. Expected it to run without problems, but crash. Did not save. (But see later comment, when I did save at this point.)
4. Responded to Colab message "Restart Runtime" in step 3, by restarting Runtime, and then "Run all": result was no "Restart Runtime" message this time, but crash with a different traceback. Saved result in file name starting "master" see attached.
5. Edit "workers=8" to "workers=1" twice in code cells. Remove all outputs. Restart runtime. Run all. Crash. Save result in file name starting "worker" see attached.

_If there was a crash, please include the traceback here._
[master_restarted_shows_bug_idars.ipynb.txt](https://github.com/TissueImageAnalytics/tiatoolbox/files/8815847/master_restarted_shows_bug_idars.ipynb.txt)
[workers=1_restarted_shows_bug_idars.ipynb.txt](https://github.com/TissueImageAnalytics/tiatoolbox/files/8815849/workers.1_restarted_shows_bug_idars.ipynb.txt)

Tracebacks available in attached files

**Comment by DavidBAEpstein** [comment]
@mostafajahanifar  @shaneahmed
 I don't understand what is going on, but I suspect the answer can be found in the changing Colab environment. I therefore created a new jupyter notebook on Colab, with only one line: 
!pip list > mylist
I then downloaded the mylist file, changing the name to pip_list.txt.
[pip_list.txt](https://github.com/TissueImageAnalytics/tiatoolbox/files/8834994/pip_list.txt)
I you look there you will see various torch_with_cuda packages. Also torch and its associates apparently are now available with Cuda built in, so I'm not sure why Colab uses torch+cu133 or something like that.

pip_list.txt has a lot of information, but I don't know how to use it. If I knew more, I would install all the packages in pip_list.txt in one of our own GPU machines, and then one could experiment without having to use Colab with its various disadvantages.

**Comment by DavidBAEpstein** [comment]
@shaneahmed: I attempted to fix my bugs using the results of "pip list" on Colab, but succeeded only in demonstrating to myself that it was beyond my current powers.

My issue underlines the importance of testing jnbs. My suggestion is that anyone modifying or creating a new jnb should be asked to find the result of pip list on a factory reset version of a blank notebook (in Colab one does
runtime > disconnect and delete runtime)
Then !pip list > colab_pip_list
and make colab_pip_list available to Travis.
Maybe there is already a program that takes as input a jupyter notebook and outputs a sequence of bash commands and python code snippets.

**Comment by DavidBAEpstein** [comment]
@mostafajahanifar @shaneahmed 
I have found one bug---there could be more. There is a typo in the contents of pretrained_model='resnet18-idars-tumour', namely
Missing key(s) in state_dict: "classifier.weight", "classifier.bias". 
Unexpected key(s) in state_dict: "classifer.weight", "classifer.bias". 
You will find the typo in the file data.pkl. But this is a binary file, and I do not know how it was produced.

**Comment by mostafajahanifar** [comment]
Thanks David for pointing out this important issue. After following the thread of your messages I decided to give it a go myself. So, I think I have found the source of problem, which is a VERY important, and I try to explain it here to my best.

Regarding this error:
> Missing key(s) in state_dict: "classifier.weight", "classifier.bias".
Unexpected key(s) in state_dict: "classifer.weight", "classifer.bias".

You get this, because it seems that we have updated the code to create the model without the typo (`classifer` being the typo) but links to the the files of pretrained model weights (`state_dict`) have not been corrected yet. These links should supposedly work fine with the older branch of the TIAToolbox. As the solution, I will be downloading the weights, correcting the typo in the dictionary and uploading them back again (this process has been done before for all other models in the toolbox but not for the IDaRS models).

I will let you know when I have done this and everything is ready for testing. Thanks for your patience and feedbacks.

**Comment by DavidBAEpstein** [comment]
There are in fact three (or maybe more) independent bugs in the current master version of idars.ipynb.
1) Clash of environments (see my suggested fix in your issue). Thanks for your explanation. I suspected something of this nature, which is why I did "pip list".
2) Typo "classifer". Thanks for attending to this.
3) It will currently fail with ON_GPU==False. In this case the number of workers needs to be set to zero. I have tested this fix and it works, though it takes a long time to run. We do claim that it works, so it has to work without crashing.

I am also planning to improve the removal of debris from previous runs. I think most of the notebooks might at present leave debris if execution is halted abnormally. I don't like this, although it's obviously not a major problem.

**Comment by DavidBAEpstein** [comment]
When I run these notebooks, pretrained networks are written into my files at $HOME/.tiatoolbox. What happens when the pretrained network is changed, as here. Will my files be overwritten?
    I don't like the fact that my files are changed without me being asked, but Shan assures me that this is common practice with imported packages. Also I don't see the point, since it doesn't take long to copy the file on the web. I don't see what is gained by keeping a permanent copy in my personal files without me being aware of it. It would seem more appropriate to keep a copy in the tiatoolbox repo than to insist on placing a copy in my personal file system, in a hidden directory so that one is unlikely to notice its presence.

**Comment by DavidBAEpstein** [comment]
Shan once mentioned that people will expect the notebooks to work with "Run All". Since the Colab default is to use the GPU (you have to change the runtype if you don't want GPU), I think the default on Colab should be ON_GPU = True. However Kaggle may have a different default. I think that, on Linux machines, one can check whether the machine has a GPU or not. Perhaps, to make "Run all" work in various scenarios, one needs to check environmental variables. However, when I tried that in one PR, others didn't like it, said it made the notebook look too complicated.

**Comment by DavidBAEpstein** [comment]
@mostafajahanifar You have done a lot and very quickly. I am keen to have a look at your work. Can you please let me know where to find it? Thanks

In particular, I want to look at it before the meeting this afternoon.

**Comment by John-P** [comment]
@mostafajahanifar Can I just check what the status of this is?
