### ISSUE TITLE
Example notebooks will not work with the next release

### ISSUE THREAD

**Issue by mostafajahanifar** [TissueImageAnalytics/tiatoolbox#357]
* TIA Toolbox version: 1.1.x?
* Python version: Python 3.7
* Operating System: Linux

In the new version of TIAToolbox we have dropped the support for python < 3.8, while Colab uses python=3.7. I think this means that non of example notebooks will work in Colab after merging develop in master simply because users cannot install the toolbox via `pip install tiatoolbox`. We didn't see this coming when we dropped the support of python 3.7.

One (really) nasty solution is to add a cell on the top of the notebook in which we install a Python 3.8 using Conda, like this
```
!wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh
!chmod +x mini.sh
!bash ./mini.sh -b -f -p /usr/local
!conda install -q -y jupyter
!conda install -q -y google-colab -c conda-forge
!python -m ipykernel install --name "py38" --user
```
however, this is not idea at all because it's not guaranteed to work all the time and there might be tons of problems with dependencies. Alternatively, we can consider having support for Python 3.7 back, if possible.

**Comment by DavidBAEpstein** [comment]
When a JNB is run ons on Kaggle or Colab the environment needs to be the same in all essentials as the tiatoolbox environment. So, start with finding out which platform one is working on in the first code cell, and install good versions of python and pip. Perhaps nothing else would be necessary.

**Comment by mostafajahanifar** [comment]
There are different ways to do it. This one didn't work for me. The one that I have posted above did, however, when installing TIAToolbox on the new python 3.8 environment it will give an error complaining about another package (it might get resolved if we use Python 3.9 or try installing other packages separately, but nothing is guaranteed to work anyway). Therefore, these not really good way to deal with the problem. I will look further into your suggested solution anyway.

**Comment by mostafajahanifar** [comment]
I found a hacky way to fix this problem:
1- First we need to download the notebook we want to fix and open it with a text editor and change the kernel specifics key as follows to make Colab initialize a new environment:
```
"kernelspec": {
  "name": "py38",
  "display_name": "Python 3.8"
}
```
2- Install the desired python version with ipykernel and jupyter via Conda:
```
!wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh
!chmod +x mini.sh
!bash ./mini.sh -b -f -p /usr/local
!conda install -q -y jupyter
!conda install -q -y google-colab -c conda-forge
!python -m ipykernel install --name "py38" --user
```
3- Refresh the browser (not restarting the kernel, but refreshing the browser page)

Then you will have Colab kernel loaded with Python 3.8. What I like about this solution is that it will give you a fresh environment in which you can install whatever you want but still you might face some dependency issues as Conda envs come with some preinstalled packages (might be able to avoid this by installing a new env without conda).

However, there are many disadvantages:
1- It's hacky and a pain to do for all notebooks. The installation would require a refresh and then a runtime restart after the installation of the tiatoolbox.
2- Cell execution does not work all the time, especially if you want to run the same cell twice.
3- It's not guaranteed to work all the time and might break for lots of applications.
I will look more into this solution to see if it's still something we want to go with. I'm still in favour of keeping support for Python 3.7!

**Comment by shaneahmed** [comment]
@mostafajahanifar I am adding support for Python 3.7 back for now. Once Colab starts supporting Python 3.8 we will remove Python 3.7 support.

**Comment by mostafajahanifar** [comment]
Thanks Shan and David for your attention. Now that we are keeping the support for Python 3.7, we can close this issue.

**Comment by jwnimmer-tri** [comment]
In case it helps, I can also highly recommend https://deepnote.com/ for hosting example notebooks.  When Google stopped maintaining Colab, I switched my project's example notebooks to Deepnote and I couldn't be happier.
