### ISSUE TITLE
Request to list sample WSIs available

### ISSUE THREAD

**Issue by 99snowleopards** [TissueImageAnalytics/tiatoolbox#364]
### Description

thank you for releasing this amazing library! would it be possible to list all the WSIs that are available for download in the sample folder here: `https://tiatoolbox.dcs.warwick.ac.uk/sample_wsis/`

it'd make it a lot easier to test the public notebooks on different images,

### What I Did

```
import requests

tia_url = "https://tiatoolbox.dcs.warwick.ac.uk/sample_wsis/"
page_content = requests.get(tia_url).text
```

thank you

**Comment by vqdang** [comment]
Hi, the test data and the pretrained models are provided here in the yaml file:
https://github.com/TissueImageAnalytics/tiatoolbox/tree/develop/tiatoolbox/data

You can use this function to fetch pretrained weights:
https://github.com/TissueImageAnalytics/tiatoolbox/blob/9815feb9cb9e55a9e28d0b1cf362e8fa0827a559/tiatoolbox/models/architecture/__init__.py#L19

As for the wsi etc., you can use this one:
https://github.com/TissueImageAnalytics/tiatoolbox/blob/9815feb9cb9e55a9e28d0b1cf362e8fa0827a559/tiatoolbox/data/__init__.py#L27

**Comment by 99snowleopards** [comment]
thank you so much @vqdang - I had not seen that yaml file!
