### ISSUE TITLE
Replace recommonmark, possibly with MyST-Parser

### ISSUE THREAD

**Issue by DavidBAEpstein** [TissueImageAnalytics/tiatoolbox#388]
Output from `tiatoolbox --version`
tiatoolbox 1.1.0 (Python 3.1) on macOS-11.6.7-x86_64-i386-64bit.

### Description
*make html* in docs produces so much *cry wolf* type of noise that possibly important information is ignored. I haven't found the source of all the noise, but a significant amount comes from the obsolete and unsupported python package recommonmark. See https://github.com/readthedocs/recommonmark/issues/221
with information from one of the authors of recommonmark.

I don't know how much work it would be to replace recommonmark by a properly maintained parser, and others would have to judge.

**Comment by shaneahmed** [comment]
Fixed in #441 and #447
