### ISSUE TITLE
how to use pretrained models using the Kather 100k datasets for a transfer learning task

### ISSUE THREAD

**Issue by CindyQi7788** [TissueImageAnalytics/tiatoolbox#411]
* TIA Toolbox version: tiatoolbox 1.0.1
* Python version: 3.9.7
* Operating System: Mac

### Description

I would like to use Tiatoolbox's those pretrained models using the Kather 100k datasets for another pathology dataset for a classification or regression task with transfer learning. 

How to load those pretrained models from tiatoolbox for a transfer learning?

Looking forward to your reply and thank you very much.
Xin

**Comment by vqdang** [comment]
Hi, you can refer to this to see how transfer learning can be done for normal CNN https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html .

Once you read that tutorial, you need to download the associated weights for the toolbox model you want to tune. This can be achieved by

```
import torch
from tiatoolbox.models.architecture.vanilla import CNNModel

pretrained_weights = "PATH"
pretrained_weights = torch.load(pretrained_weights, map_location="cpu")

model = CNNModel("resnet50", num_classes=6)
model.load_state_dict(pretrained_weights, strict=False)

```

Then, you need to further modify that `model` accordingly for your needs. You can refer to here as an example https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html#convnet-as-fixed-feature-extractor.

The weights can be downloaded directly from the using the urls mentioned here https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/tiatoolbox/data/pretrained_model.yaml . For example, using the `resnet50` as above:
> https://github.com/TissueImageAnalytics/tiatoolbox/blob/93004812ee0211e770ee596d8c7dd340c2410dec/tiatoolbox/data/pretrained_model.yaml#L44
