### ISSUE TITLE
WSI Automatic tissue detection

### ISSUE THREAD

**Issue by rjesud** [TissueImageAnalytics/tiatoolbox#433]
Thanks for creating such a useful tool! Ready access to pretrained hovernet models has been a big help with our projects. 

I have a question related to WSI prediction. I have experienced extremely long processing times for an H&E image with dimensions (36480, 26496). I am using GPU processing but the time exceeds 8hrs. I thought one issue might be the fact that I did not do tissue detection so the predictor is wasting time on glass regions. 

In  NucleusInstanceSegmentor() I see there is an option to auto-generate a mask. If I set this as true, how do I tell the predict function to use this mask? I see the predict function has an arguement to define a path of a mask. Where is the auto generated mask saved?

**Comment by shaneahmed** [comment]
If you would like to save the mask, you can generate it using https://github.com/TissueImageAnalytics/tiatoolbox/blob/af7319ef633e2f8b315b0949ed343f67d38bab0a/tiatoolbox/models/engine/semantic_segmentor.py#L684. You can then pass this to the model and it will enable it to visualise this.
