### ISSUE TITLE
PatchExtractor filtering

### ISSUE THREAD

**Issue by rogertrullo** [TissueImageAnalytics/tiatoolbox#446]
* TIA Toolbox version: 1.2.1
* Python version: 3.8
* Operating System:  ubuntu 20

### Description
Hi, thanks for sharing this library!
I was checking the  [PatchExtractor class](https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/tiatoolbox/tools/patchextraction.py) and it seems that patches containing at least one pixel of positive mask, will be included.
Depending on the scenario this can be undesired e.g. some patches will be mainly background.
I was wondering if we can include some kind of parameter e.g. min number of positive pixels or minimum area of the patch being positive?

**Comment by shaneahmed** [comment]
@mostafajahanifar Please can you look into this?

**Comment by rogertrullo** [comment]
@mostafajahanifar if it can help, I added a simple PR [#451 ](https://github.com/TissueImageAnalytics/tiatoolbox/pull/451) of what it could look like
