### ISSUE TITLE
MyST parser

### ISSUE THREAD

**Issue by DavidBAEpstein** [TissueImageAnalytics/tiatoolbox#448]
- Operating System: Macos 12.5.1
- virtual environment tiatoolbox-dev

`make html` requires `myst_parser`. This package is not listed in any of the requirements files at the top level of `tiatoolbox`.

**Comment by shaneahmed** [comment]
This file is required for building docs and therefore is listed under `docs/requirements.txt`
https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/docs/requirements.txt

**Comment by John-P** [comment]
Perhaps we should also add it to the dev requirements, simply to avoid people having to install from two requirements files (/requirements_dev.txt and /doc/requirements.txt) when setting up an environment. Else, we can just update the documentation to mention the second requirements file under /docs.

**Comment by shaneahmed** [comment]
#447 adds sphinx related dependencies to `requirements_dev.txt`, `requirements.dev.conda.yml` and `docs/requirements.txt`
