### ISSUE TITLE
Can TIAtoolbox support ".TMAP" formatted WSI file?

### ISSUE THREAD

**Issue by liuxiaoping2020** [TissueImageAnalytics/tiatoolbox#462]
Dear author,

Thank you for reading my email. I am a medical stall from China. 

Recently, I found that Tiatoolbox is awesome program for digital pathology. In order to benefit more researchers and pathologists with TIAtoolbox, I have some suggestions for you to improve tiatoolbox. I wonder to know  whether the tiatoolbox supports ".TMAP" formatted WSI file? As we know, WSI files in "TMAP" format are very common in China. If tiatoolbox cannot support files in "TMAP" format, its application scope will be greatly limited.  The ".TMAP" might be produced by a company called Unic Technologies (http://www.unic-tech.cn/). There's a Chinese patent describing the file format (https://patentimages.storage.googleapis.com/c2/8b/72/b592fc756af7b4/CN1928871A.pdf). English version here (https://patents.google.com/patent/CN100429658C/en).

And a sample ".TMAP" formatted WSI is available at https://drive.google.com/file/d/1URrrS3m6qPyGCJ2XG_hcyYIMOpqypV-M/view?usp=sharing

Can you help make tiatoolbox support WSIs in ".TMAP" ?

Looking forward to your reply

Best regards
Xiaoping

**Comment by shaneahmed** [comment]
Thanks @liuxiaoping2020 
We haven't seen these images before. Please can you share any sample code/source code or a relevant library to read these images?

Alternatively you can create a PR to add a reader for this file format. Or use bioformats/other library to read the images. A gist is available at this link https://gist.github.com/John-P/7da4224d76eedfd6a5f6239589acaf2f

**Comment by shaneahmed** [comment]
We are going to close this issue. Please feel free to reopen if you have anything to respond.
