### ISSUE TITLE
Two README.md files is too many

### ISSUE THREAD

**Issue by DavidBAEpstein** [TissueImageAnalytics/tiatoolbox#472]
There is a README.md file in the root directory and another in the examples directory.  All nine notebooks in the examples directory display what looks like a simple link to the README file in the examples directory. HOWEVER, it is in fact a link to the other README file in the root directory. This is confusing, and is likely to have the result that the examples/README.md file is never read, never referred to and never used.

Perhaps the examples/README.md file should be renamed. Or, maybe better, the "click here" text for the link should be disambiguated.

**Comment by shaneahmed** [comment]
Hi @DavidBAEpstein This is the how GitHub Rendering works. If we rename examples/README.md then the display on the examples page will be lost. If we want to retain that then we will need to keep this name.

**Comment by DavidBAEpstein** [comment]
@shaneahmed I'm happy with keeping the name of the file. But the text in the notebook should make it clear which README file is being cited.
Second point: I haven't looked at examples/README.md but presumably there should be links to it from the notebooks in the examples directory. At the moment, I think that no such link appears in any of the notebooks.
