### ISSUE TITLE
Add Image Writer

### ISSUE THREAD

**Issue by rogertrullo** [TissueImageAnalytics/tiatoolbox#491]
### Description

Hi, I was wondering if we can try to implement an image writer. There are multiple readers but no writers. I think it can be interesting to have the possibility of writing images to disk, say for example write a  `VirtualWSIReader` object as `ome.tiff`

**Comment by shaneahmed** [comment]
We will be integrating an ome.zarr writer using https://github.com/John-P/wsic. We will not be adding support for ome.tiff as this will be replaced by ome.zarr in future. However, wsic supports ome.tiff writer.

**Comment by shaneahmed** [comment]
Closing for now. We can discuss it further if you have any issue. We would recommend using https://github.com/John-P/wsic for writing.
