### ISSUE TITLE
Issues with Pyramidal .tiffs

### ISSUE THREAD

**Issue by 16nbb1** [TissueImageAnalytics/tiatoolbox#495]
### Description

Hello! I'm having some difficulties reading in pyramidal .tiff files. Below, I've attached screenshots of what I've tried and the errors. 

![Screenshot from 2022-10-20 17-53-09](https://user-images.githubusercontent.com/68873262/197197651-451faf59-4700-4cba-982f-903a033251d4.png)

As you can see, it's using OpenSlideWSIReader, even though I'm requesting TIFFSWIReader. 

<img width="867" alt="Screen Shot 2022-10-21 at 8 35 51 AM" src="https://user-images.githubusercontent.com/68873262/197197960-9c49eb85-6941-4816-acf6-e226b5bea5e3.png">

Additionally, I'm having issues accessing the image at different levels of resolution.
Thanks so much!

**Comment by John-P** [comment]
@16nbb1 Hi there, it might be difficult to replicate this without knowing the image file you are trying to open. Is it possible to share it?
