### ISSUE TITLE
Example to train my own data from scratch

### ISSUE THREAD

**Issue by OmarAshkar** [TissueImageAnalytics/tiatoolbox#516]
### Description

I have large WSI files and the corresponding multiclass masks. I want to be able to feed the files and the masks to train my own hovernet.

I looked at the example notebooks. All of them basically infer on test images with pre-trained model without training from the beginning.

Best Regards,
Omar

**Comment by shaneahmed** [comment]
Hi Omar,
Please use the [hovernet repo](https://github.com/vqdang/hover_net) which has detailed description on training new models from scratch.
