### ISSUE TITLE
How to implement custom HoVer-Net Model in TIA ToolBox to segment nuclei?

### ISSUE THREAD

**Issue by WilliWespe** [TissueImageAnalytics/tiatoolbox#521]
- TIA Toolbox version: 1.3.0
- Python version: 3.9.12
- Operating System: jupyter notebook on linux hpc cluster

### Description

I used the [08-nucleus-instance-sgmentation.ipynb](https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/examples/08-nucleus-instance-segmentation.ipynb) to segment nuclei. My dataset looks slightly different, than the pannuke dataset. So I used this [tutorial](https://pathml.readthedocs.io/en/latest/examples/link_train_hovernet.html) to augment the pannuke dataset so that it looks like mine, and trained a new HoVer-Net model. The output i got is a .pt file.

Now I want to use my custom HoVer-Net model in the TIA ToolBox to segment nuclei.

How do I do that?
Does anybody know, or has a link to an explanation/tutorial?

**Comment by shaneahmed** [comment]
you can include your architecture file [architecture](https://github.com/TissueImageAnalytics/tiatoolbox/tree/develop/tiatoolbox/models/architecture) and define the model which inherits [ModelABC](https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/tiatoolbox/models/models_abc.py).

Even better if you train the model using [hovernet_original](https://github.com/vqdang/hover_net) and just load the weights file using pretrained_weights option in the NucleusInstanceSegmentator.
