### ISSUE TITLE
`slide_thumbnail` method does not work properly with DICOM WSIs

### ISSUE THREAD

**Issue by mostafajahanifar** [TissueImageAnalytics/tiatoolbox#529]
- TIA Toolbox version: 1.3
- Python version: 3.10
- Operating System: Ubuntu

### Description

When reading a DICOM slide and trying to use `slide_thumbnail` to get the slide thumbnail at a certain resolution, it does not work properly and instead of giving the slide thumbnail, it returns a region of the slide which seems to be extracted from the baseline resolution.

### What I Did

```
wsi = WSIReader('path_to_sample.dicom')
thumb = wsi.slide_thumnail(resolution=8, units='mpp')
```

p.s.
I checked the same slide with `wsidicom` library and the `slide_thumbnail` of that library works just fine.

**Comment by mostafajahanifar** [comment]
[update]

I just checked this on Windows OS as well with TIAToolbox v1.3.3, and the same problem persists. Can anyone else try it please?

**Comment by measty** [comment]
I made a PR that maybe fixes this (my knowledge of DICOM isnt good enough for me to be sure, but seems to work). https://github.com/TissueImageAnalytics/tiatoolbox/pull/564
