### ISSUE TITLE
Getting the results of NucleusInstanceSegmentor without going through a file.

### ISSUE THREAD

**Issue by dakomura** [TissueImageAnalytics/tiatoolbox#531]
Hi,
Is there a way to input a numpy array of image data into NucleusInstanceSegmentor and get the result as a variable without going through a file?
I want to use this functionality as a preprocessor in my python script.

**Comment by shaneahmed** [comment]
you can check this [test_hovernet](https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/tests/models/test_hovernet.py)

**Comment by dakomura** [comment]
@shaneahmed Thank you very much!!

**Comment by dakomura** [comment]
Hi,
I have got the segmentation results from HoverNet models. 
Is it possible to get the instance information from the results?

**Comment by adamshephard** [comment]
Hi,

Thanks for your interest in our toolbox. If you have the segmentation results from hovernet stored as a .dat file, you can read the results by following the instructions in the Nucleus Instance Segmentor example [notebook](https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/examples/08-nucleus-instance-segmentation.ipynb). If inference has been done on the WSI-level then please refer to the "Inference on WSIs" section. If it's been done at the tile-level then "Inference on tiles".

I hope this helps solve your problem.

Thanks,
Adam
