### ISSUE TITLE
Documentation inconistency

### ISSUE THREAD

**Issue by blaginin** [TissueImageAnalytics/tiatoolbox#532]
- TIA Toolbox version: 1.3.1, dev
- Python version: 3.10.8 (conda)
- Operating System: MacOS 13.1 (22C65)

### Description

Trying to learn the library and discovered some cases where docs are inconsistent with the current behaviour. 

### What I Did

- [x] Tried to create `AnnotationStore` (as it was stated [here](https://github.com/TissueImageAnalytics/tiatoolbox/blob/76fcfff0593e4dbb55c0bc58b687d3788cdd33e3/tiatoolbox/annotation/storage.py#L833), [here](https://github.com/TissueImageAnalytics/tiatoolbox/blob/76fcfff0593e4dbb55c0bc58b687d3788cdd33e3/tiatoolbox/annotation/storage.py#L920), [here](https://github.com/TissueImageAnalytics/tiatoolbox/blob/76fcfff0593e4dbb55c0bc58b687d3788cdd33e3/tiatoolbox/annotation/storage.py#L931), [here](https://github.com/TissueImageAnalytics/tiatoolbox/blob/76fcfff0593e4dbb55c0bc58b687d3788cdd33e3/tiatoolbox/annotation/storage.py#L2153), [here](https://github.com/TissueImageAnalytics/tiatoolbox/blob/76fcfff0593e4dbb55c0bc58b687d3788cdd33e3/tiatoolbox/annotation/storage.py#L2408), and [here](https://github.com/TissueImageAnalytics/tiatoolbox/blob/76fcfff0593e4dbb55c0bc58b687d3788cdd33e3/tiatoolbox/annotation/storage.py#L2408)).
```python
>>>  store = AnnotationStore()
TypeError: Can't instantiate abstract class AnnotationStore with abstract methods __getitem__, __len__, __setitem__, commit, dump, dumps, open
```
`AnnotationStore` has become abstract, and it would be helpful to update the docs accordingly. Examples can either state that users must use derived classes or explicitly show methods usage on `SQLiteStore` or `DictionaryStore`.

- [x] Tried to add an object to my `AnnotationStore` (as it was stated [here](https://github.com/TissueImageAnalytics/tiatoolbox/blob/76fcfff0593e4dbb55c0bc58b687d3788cdd33e3/tiatoolbox/annotation/storage.py#L834), [here](https://github.com/TissueImageAnalytics/tiatoolbox/blob/76fcfff0593e4dbb55c0bc58b687d3788cdd33e3/tiatoolbox/annotation/storage.py#L920), [here](https://github.com/TissueImageAnalytics/tiatoolbox/blob/76fcfff0593e4dbb55c0bc58b687d3788cdd33e3/tiatoolbox/annotation/storage.py#L931), [here](https://github.com/TissueImageAnalytics/tiatoolbox/blob/76fcfff0593e4dbb55c0bc58b687d3788cdd33e3/tiatoolbox/annotation/storage.py#L2153), [here](https://github.com/TissueImageAnalytics/tiatoolbox/blob/76fcfff0593e4dbb55c0bc58b687d3788cdd33e3/tiatoolbox/annotation/storage.py#L2408), and [here](https://github.com/TissueImageAnalytics/tiatoolbox/blob/76fcfff0593e4dbb55c0bc58b687d3788cdd33e3/tiatoolbox/annotation/storage.py#L2408)).
```python
>>> store = DictionaryStore()
>>> store.add(
...     Annotation(
...         geometry=Polygon.from_bounds(0, 0, 1, 1),
...         properties={"class": 42},
...     ),
...     key="foo",
... )
AttributeError: 'DictionaryStore' object has no attribute 'add'
```
It looks like `.add` → `.append`?

- [x] Tried to query my `AnnotationStore` (as it was stated [here](https://github.com/TissueImageAnalytics/tiatoolbox/blob/76fcfff0593e4dbb55c0bc58b687d3788cdd33e3/tiatoolbox/annotation/storage.py#L2161) and [here](https://github.com/TissueImageAnalytics/tiatoolbox/blob/76fcfff0593e4dbb55c0bc58b687d3788cdd33e3/tiatoolbox/annotation/storage.py#L841)).
```python
>>> store = DictionaryStore()
>>> store.append(
...     Annotation(
...         geometry=Polygon.from_bounds(0, 0, 1, 1),
...         properties={"class": 42},
...     ),
...     key="foo",
... )
>>> store.bquery(where="props['class'] == 42") 
AttributeError: 'NoneType' object has no attribute 'bounds'
```
The method works successfully with `SQLiteStore` but fails on `DictionaryStore`. Maybe it would be helpful to add a test for that behaviour.

- [ ] Tried to predict classes of batches (as it was stated [here](https://github.com/TissueImageAnalytics/tiatoolbox/blob/73f9d1f4372e8b680ef636de95c8589fa4e8d61a/tiatoolbox/models/engine/patch_predictor.py#L532))
```python
>>> wsi_data = wsi.slide_thumbnail(resolution=5, units="power")
>>> assert type(wsi_data) == np.ndarray

>>> predictor = PatchPredictor(pretrained_model="resnet18-kather100k", batch_size=32)
>>> tile_output = predictor.predict(
...    imgs=[wsi_data],
...    mode="tile",
...    merge_predictions=True,
...    patch_input_shape=[224, 224],
...    stride_shape=[224, 224],
...    resolution=1,
...    units="baseline",
...    return_probabilities=True,
...    on_gpu=False
... )
TypeError: expected str, bytes or os.PathLike object, not ndarray
```
The method works with filenames but not with `ndarray` objects. Thus, users have to save their intermediate images to call the methods, which seems like an extra step.

**Comment by shaneahmed** [comment]
@blaginin Please create a PR to suggest edits to the documentation. You can also look at #540 if you have any suggestions.

**Comment by shaneahmed** [comment]
Hi @blaginin, Do you have any comments on #565 ?

**Comment by blaginin** [comment]
> Hi @blaginin, Do you have any comments on #565 ?

@shaneahmed, all fixed except the last point. I can change it in a separate PR.
