### ISSUE TITLE
Problem in calculating prob in defining loop in slideGraph

### ISSUE THREAD

**Issue by fariba888** [TissueImageAnalytics/tiatoolbox#533]
In the slide-graph.ipynb for calculating prob in defining the loop 'prob = scaler.predict_proba(np.array(logit, ndmin=2).T)[:, 0]' is used and it causes to decrease auc and prc during training. However in inference part prob is calculated using prob = scaler.predict_proba(np.array(logit, ndmin=2).T)[:, 1]. Could you please help me to understand this part?

**Comment by fariba888** [comment]
In the slide-graph.ipynb for calculating prob in defining the loop 'prob = scaler.predict_proba(np.array(logit, ndmin=2).T)[:, 0]' is used and it causes to decrease auc and prc during training. However in inference part prob is calculated using prob = scaler.predict_proba(np.array(logit, ndmin=2).T)[:, 1]. Could you please help me to understand this part?

**Comment by shaneahmed** [comment]
I am closing this issue for now as this doesn't require any changes in the code. If you need improved documentation we can help with this. Please contact [Fayyaz Minhas](https://warwick.ac.uk/fac/sci/dcs/people/fayyaz_minhas/) senior author of SlideGraph if you need help with the algorithm.
