### ISSUE TITLE
Hovernet gives background false positive

### ISSUE THREAD

**Issue by OmarAshkar** [TissueImageAnalytics/tiatoolbox#570]
- TIA Toolbox version: 1.3
- Python version: 3.10
- Operating System: Ubuntu 22.04

### Description
I am trying to train hovernet from scratch giving my own labelled dataset. I have a problem that in my slides there is some stain artifact that I have labelled as background (class 0). However, during inference, I get this class mistakenly labelled 1. 

Any ideas if this could be fixed?

**Comment by shaneahmed** [comment]
Hi Omar, I would suggest to raise this issue here https://github.com/vqdang/hover_net.
