### ISSUE TITLE
Issue in ImageFont.py

### ISSUE THREAD

**Issue by MyYo** [TissueImageAnalytics/tiatoolbox#595]
- TIA Toolbox version: head
- Python version: Whatever is installed on Colab
- Operating System: Colab

### Description

I tried to run the demo provided in the following link in Colab "as is", didn't change anything just click the colab link and hit run
https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/examples/08-nucleus-instance-segmentation.ipynb

### What I Did

Just hit run all 

I got the following error message pointed at this cell:
from tiatoolbox.models.engine.nucleus_instance_segmentor import NucleusInstanceSegmentor

Error message reads
from ._util import isDirectory, isPath, py3
ImportError: cannot import name 'py3' from 'PIL._util' (/usr/local/lib/python3.9/dist-packages/PIL/_util.py)

A short stackoverflow didn't bring much unfortinetly.

**Comment by shaneahmed** [comment]
You need to restart runtime after installation on Google Colab as mentioned in the Notebook.

![image](https://user-images.githubusercontent.com/13048456/235120995-980b6a2b-dd1a-49c6-8724-293d958f7176.png)
