### ISSUE TITLE
Issues with reproducing the result in examples/inference-pipelines/slide-graph.ipynb 

### ISSUE THREAD

**Issue by mohsuliman** [TissueImageAnalytics/tiatoolbox#602]
- TIA Toolbox version: 1.3.3
- Python version: 3.9.16
- Operating System: Ubuntu 18.04.6

### Description

I am trying to reproduce the results given at examples/inference-pipelines/slide-graph.ipynb using FEATURE_MODE = "composition". I have left everything in the code unchanged and set NUM_NODE_FEATURES =4 to match the given graph.

I have encountered the following two issues: 

1- Running the code unchanged gives me the following error in the code line that has "holder[uids] = freqs"

```
IndexError: arrays used as indices must be of integer (or boolean) type
```

Forcing the type of "uids" to be int seems to solve the issue, but I wonder why I have this error in the first place?

2- The second issue is that I am not getting a graph that matches the already provided graph. The network generates nodes with all zero features in the regions ruled out by the mask (i.e., where we shouldn't have any nodes) and assign edges to them as well. Hence, my final image graph has nodes (with edges) everywhere in the image. Also, as opposed to what is suggested in the notebook, the code's run time takes more than 7 hours. Am I missing something fundamental here?

**Comment by shaneahmed** [comment]
Have you tried running the notebook on Colab? I just ran it on Colab and it runs fine for me without errors.

**Comment by mohsuliman** [comment]
@shaneahmed  thanks for the reply. 

I am not sure if i can run it in Colab. Running the cell (In [12]) takes more than 4 hours and then Colab disconnects (as I don't have Colab Pro). Again running it in my local GPU it takes more than 7 hours. 

how long does it take to run the cell In [12]. It

**Comment by mohsuliman** [comment]
@shaneahmed 

The only change that I have made in Colab is that i commented the part:
```
 # ! for using pre-generated graph
NUM_NODE_FEATURES = 4
FEATURE_MODE = "composition"
USE_PRE_GENERATED = True
```

and uncommented the part of:
```
# ! for trying out the function
NUM_NODE_FEATURES = 5
FEATURE_MODE = "composition"
USE_PRE_GENERATED = False
```

**Comment by mohsuliman** [comment]
@shaneahmed  Yes, I have done all these steps and the issue is still there. Just tried it again and it went over 4 hours before Colab run stopped. What else could be the problem :/ 

I am not sure how is it taking 5 min on your Colab. It is mentioned here that "composition" may take over an hour (which is also not the case for me)
<img width="1046" alt="Screenshot 2023-05-09 at 11 11 00 pm" src="https://github.com/TissueImageAnalytics/tiatoolbox/assets/132899972/0ea02a62-7664-4538-a8d2-d25d88b350ce">

**Comment by shaneahmed** [comment]
As you are using USE_PRE_GENERATED = False it's taking longer

**Comment by maes21353** [comment]
@shaneahmed  Are you able to run the code in Colab after setting USE_PRE_GENERATED = False and FEATURE_MODE = "composition" and get the same results as the one provided in the download folder within the 1 hour time frame suggested?

Your help is highly appreciated. @John-P

**Comment by shaneahmed** [comment]
We will look into this in due time.

**Comment by measty** [comment]
There are a few problems with this:

1. It uses the shapely SRtree which changed in recent shapely versions, so needs an update to deal with that
2. In the cell composition calculation, it isn't doing the filtering by mask after generating the patch locations. The deep feature bit doesn't need it as its handled in the DeepFeatureExtractor, but for the cell composition where its generating the patch locations manually, it needs to call filter_coordinates after calling get_coordinates in order to filter for points in the mask only

**Comment by measty** [comment]
Making changes in #608 to fix these issues

**Comment by mohsuliman** [comment]
Thanks @measty and @shaneahmed for the updating the code. 

Just finished testing the new updated version. 

When the code calls:

```
# filter out coords which dont lie in mask
    selected_coord_indices = PatchExtractor.filter_coordinates(
        WSIReader.open(mask_path),
        patch_inputs,
        wsi_shape=wsi_shape,
        min_mask_ratio=0.5,
    )
```
I got the following error:

```
TypeError: filter_coordinates() got an unexpected keyword argument 'wsi_shape'
```

As a reminder I am setting USE_PRE_GENERATED = False and FEATURE_MODE =  "composition"

**Comment by measty** [comment]
> Thanks @measty and @shaneahmed for updating the code.
> 
> Just finished testing the new updated version.
> 
> When the code calls:
> 
> ```
> # filter out coords which dont lie in mask
>     selected_coord_indices = PatchExtractor.filter_coordinates(
>         WSIReader.open(mask_path),
>         patch_inputs,
>         wsi_shape=wsi_shape,
>         min_mask_ratio=0.5,
>     )
> ```
> 
> I got the following error:
> 
> ```
> TypeError: filter_coordinates() got an unexpected keyword argument 'wsi_shape'
> ```
> 
> As a reminder I am setting USE_PRE_GENERATED = False and FEATURE_MODE = "composition"

Hi,

It sounds like you might be using an older version of tiatoolbox, that function changed in recent versions. Could you check you are using the most recent release, and see if the error still re-occurs?

**Comment by mohsuliman** [comment]
Thanks @measty. I have updated tiatoolbox version. But now when executing

```
selected_coord_indices = PatchExtractor.filter_coordinates(
        WSIReader.open(mask_path),
        patch_inputs,
        wsi_shape=wsi_shape,
        min_mask_ratio=0.5,
    )
```
using the provided sample.svs and sample_mask.png, i got the following error: 
```
 ............../tiatoolbox/tools/patchextraction.py:289 in filter_coordinates
    scale_factors = np.array(tissue_mask.shape[::-1]) / np.array(wsi_shape)

ValueError: operands could not be broadcast together with shapes (3,) (2,)
```
I believe that the provided mask dimension has to be reshaped.  Currently it is 3D array. Maybe obtaining a 2D mask ? 


On a different topic, I have tried to test the code on a different WSI with the following info:

```
{'objective_power': 40.0,
 'slide_dimensions': (71712, 78507),
 'level_count': 4,
 'level_dimensions': ((71712, 78507),
  (17928, 19626),
  (4482, 4906),
  (2241, 2453)),
 'level_downsamples': [1.0,
  4.000076429226536,
  16.001121076233183,
  32.002242152466366],
 'vendor': 'aperio',
 'mpp': (0.2519, 0.2519),
 'file_path': PosixPath('path/to/WSI'),
 'axes': 'YXS'}
```

But I keep getting the following Warnings: 

```
[WARNING] Read: Scale > 1.This means that the desired resolution is higher than the WSI baseline
(maximum encoded resolution). Interpolation of read regions may occur.
```

Do you have any comment on that (although I have tried a different resolution factor)?

**Comment by measty** [comment]
Hi @mohsuliman,

> ValueError: operands could not be broadcast together with shapes (3,) (2,)
> 
> I believe that the provided mask dimension has to be reshaped. Currently it is 3D array. Maybe obtaining a 2D mask ?

There is a change included in the PR #608 that allows 3D masks as well as 2D masks.

> But I keep getting the following Warnings:
> 
> [WARNING] Read: Scale > 1.This means that the desired resolution is higher than the WSI baseline
> (maximum encoded resolution). Interpolation of read regions may occur.

This warning can safely be ignored most of the time. It's there to provide a heads up that a slide is being read at a lower resolution than the requested resolution, and is being upscaled (with interpolation) to the desired read mpp. In your case, because the requested resolution is 0.25 mpp and the slide base res is 0.2519 mpp (slightly lower res), the warning appears, but it isn't a problem

**Comment by mohsuliman** [comment]
> Hi @mohsuliman,
> 
> > ValueError: operands could not be broadcast together with shapes (3,) (2,)
> > I believe that the provided mask dimension has to be reshaped. Currently it is 3D array. Maybe obtaining a 2D mask ?
> 
> There is a change included in the PR #608 that allows 3D masks as well as 2D masks.
> 
> > But I keep getting the following Warnings:
> > [WARNING] Read: Scale > 1.This means that the desired resolution is higher than the WSI baseline
> > (maximum encoded resolution). Interpolation of read regions may occur.
> 
> This warning can safely be ignored most of the time. It's there to provide a heads up that a slide is being read at a lower resolution than the requested resolution, and is being upscaled (with interpolation) to the desired read mpp. In your case, because the requested resolution is 0.25 mpp and the slide base res is 0.2519 mpp (slightly lower res), the warning appears, but it isn't a problem

Thanks @measty. I have tested that again and the error is still there. 

In the main code, and when you call 

```
selected_coord_indices = PatchExtractor.filter_coordinates(
        WSIReader.open(mask_path),
        patch_inputs,
        wsi_shape=wsi_shape,
        min_mask_ratio=0.5,
    )
```

you are passing the mask, i.e., WSIReader.open(mask_path) which is of 3D, to the patchextraction.py script (passed as mask_reader variable). At the patchextraction.py script we have:

```
tissue_mask = mask_reader.img
scale_factors = np.array(tissue_mask.shape[::-1]) / np.array(wsi_shape)
```
More preciously, the sample_mask.png provided in the download folder gives
```
tissue_mask.shape = (3828, 4105, 3)
```
while 
```
wsi_shape = array([64532, 60184])
```

Hence, will always have:
```
np.array(tissue_mask.shape[::-1]).shape = (3,)

np.array(wsi_shape).shape = (2,)
```
which justifies the error:

```
ValueError: operands could not be broadcast together with shapes (3,) (2,)

```

**Comment by mohsuliman** [comment]
Thanks, @measty, for the continuous help. The result is still not the same as the provided one in the download folder. More specifically, "composition" mode generates nodes in areas with no tissues (as highlighted in the figures below). There might be more updates coming to the code that I am missing. Will be happy to wait for them if that is the case. (Side note: you might want to update NODE_SIZE in the code. The result below IS obtained using NODE_SIZE=14 AS 24 was too big)
![Graph_1](https://github.com/TissueImageAnalytics/tiatoolbox/assets/132899972/3d90beba-4b3e-41f0-abba-6ef850e09038)

**Comment by measty** [comment]
> Thanks, @measty, for the continuous help. The result is still not the same as the provided one in the download folder. More specifically, "composition" mode generates nodes in areas with no tissues (as highlighted in the figures below). There might be more updates coming to the code that I am missing. Will be happy to wait for them if that is the case. (Side note: you might want to update NODE_SIZE value in the code. The result below is obtained using NODE_SIZE=14 as 24 was too big)

Hi @mohsuliman,
Yes, it looks like the downloadable mask does not match the downloadable graph. The mask looks like this:
![image](https://github.com/TissueImageAnalytics/tiatoolbox/assets/20169086/b573715a-ff5f-4218-93f6-c4bafdb13f51)
So the coordinate filtering is being done correctly according to the mask.

I am not the original author of this notebook, so I can't say what mask was actually used when building that pre-generated graph, but it doesn't look like it is the above mask provided with the notebook.

It is likely the result of something like the following:
```
reader = WSIReader.open(WSI_PATH)
from skimage.morphology import remove_small_objects
msk = reader.tissue_mask(method='morphological')
msk_img = msk.img
msk_img = remove_small_objects(msk_img > 0, 10000)
plt.imshow(msk_img)
```
which results in a mask which looks like this:
![image](https://github.com/TissueImageAnalytics/tiatoolbox/assets/20169086/7052037b-e5a9-4519-89e0-fbff73842aec)

which looks like it would better reproduce the gaps in the graph. That gives a graph like:
![image](https://github.com/TissueImageAnalytics/tiatoolbox/assets/20169086/07a5c317-d6bb-4aad-b203-2ba45f75712e)
It includes nodes on the black bit of tissue now though, unlike the pre-generated graph. So still not right.

the reader.tissue_mask() function is just a simple luminosity threshold based mask. Tiatoolbox also has a unet-based tissue mask model, which I might try when I have time and see if that matches the pre-generated graph better. But it may also be that the original author of the notebook used their own mask generation code, in which case we may not be able to find out the exact mask used.

**Comment by mohsuliman** [comment]
Thanks, @measty, for the help on this. That describes everything :)
A link to the unet-based tissue mask model code will be much appreciated. Would love to investigate that as well. 

Once again, thanks for the continuous help and for answering all my questions.

**Comment by measty** [comment]
Hi @mohsuliman,

The tissue mask model can be used as follows:

```
from tiatoolbox.models.engine.semantic_segmentor import SemanticSegmentor

#input mpp 2.0, output mpp 8.0
masker = SemanticSegmentor(batch_size=16, num_loader_workers=4, num_postproc_workers=4, pretrained_model="fcn-tissue_mask")

output = masker.predict(imgs=[WSI_PATH], save_dir=MASK_DIR, mode="wsi")
```

then doing something like:
```
paths = list((Path(DOWNLOAD_DIR) / "mask_pred").glob("*"))
msk = np.load(paths[0])
msk = (msk[:,:,1]-msk[:,:,0]) > 0.95

from skimage.morphology import remove_small_objects, opening, closing, disk, remove_small_holes
morph_msk = opening(msk, disk(15))
morph_msk = remove_small_objects(morph_msk > 0, 10000)
morph_msk = closing(morph_msk, disk(5))
morph_msk = remove_small_holes(morph_msk, 1000)
```
gives a mask which looks good:
![image](https://github.com/TissueImageAnalytics/tiatoolbox/assets/20169086/d5a410f1-c625-44f4-b020-b7338195e226)
