### ISSUE TITLE
:monocle_face: Rename `VirtualWSIReader` Modes

### ISSUE THREAD

**Issue by blaginin** [TissueImageAnalytics/tiatoolbox#609]
- TIA Toolbox version: 1.4.0

### Description
Currently, `VirtualWSIReader` [supports](https://github.com/TissueImageAnalytics/tiatoolbox/blob/f684b863f4d309d8c2da0ae93f0ae4243e8ba650/tiatoolbox/wsicore/wsireader.py#L2597) two modes: `rgb` and `bool`:

- However, in reality, `bool` mode can process single-channel `np.uint8` images. Even now, without code modifications, it works fine on matrixes with values other than `0` or `1`. `uint8` is wider than `bool` but almost always takes the same amount of memory. 
- If someone uses it with **HSV** images, it will work just fine, except for the fact that VirtualWSIReader will be called with `mode="rgb"`, which makes no sence. 

Let's rename these modes to `single channel` and `multichannel`?

**Comment by shaneahmed** [comment]
We would suggest renaming `bool` to `categorical` and `rgb` to `brightfield`.
@blaginin Please go ahead and create a PR if you like.
