### ISSUE TITLE
Reading a very large region using WSIReader.read_rect results in crash

### ISSUE THREAD

**Issue by gafaua** [TissueImageAnalytics/tiatoolbox#615]
- TIA Toolbox version: 1.4.0
- Python version: 3.8
- Operating System: Linux Fedora

### Description

I use the standard WSIReader class to open a large .ndpi file (magnification x40, resolution of 126720 x 103680). When trying to use the read_rect method to extract a large part of the image (around 20% of the image), it crashes the Python environment.

### What I Did

```
reader = WSIReader.open(f"my_image.ndpi")

location = (x, y)
size = (w, h)

im = reader.read_rect(
    location,
    size,
)
```

**Comment by John-P** [comment]
I suspect this may be due to an out of memory error.

**Comment by gafaua** [comment]
@shaneahmed there is no error log, or at least not that I have found. When launching the script the terminal just completely crashes and closes without throwing any error.
@John-P I will try to process the image in chunks, but the weird part is that memory usage doesn't rise at all when monitoring CPU and memory utilization when launching the script. There is an intense single-core utilization for a few seconds, then a strong multi-core utilization for maybe half a second and then the shell crashes, but no or just little change to memory usage.

**Comment by shaneahmed** [comment]
Have you tried reading the image using `openslide`? As under the hood, TIAToolbox is using OpenSlide to read ndpi images.

**Comment by shaneahmed** [comment]
Closing this issue. Please feel free to reopen this if you have more details.
