### ISSUE TITLE
Issue generating WSI thumbnails from CLI

### ISSUE THREAD

**Issue by Abdol** [TissueImageAnalytics/tiatoolbox#633]
- TIA Toolbox version: 1.4.0
- Python version: 3.9.16
- Operating System: Ubuntu 22.04.2 LTS (via SSH)

### Description

Cannot generate thumbnails for WSIs in a folder containing TIFF images using the `slide-thumbnail` CLI command. I can, however, generate a thumbnail for a single TIFF WSI.

### What I Did

I have run the following command:

`tiatoolbox slide-thumbnail --img-input /home/path/to/folder/ --output-path ./slide-thumbnails`

The command ran for a while (a few seconds), created the _slide-thumbnails_ folder and then returned nothing. Expected behavior: Generate thumbnails for each WSI contained in the specified path.

However, it works when specifying a path to a single TIFF-based WSI. For instance, when running:

`tiatoolbox slide-thumbnail --img-input /home/path/to/5_ER_val.tiff --output-path ./slide-thumbnails`

The command returns the following output:

> |2023-07-04|13:49:41.062| [WARNING] /home/u2271662/.local/lib/python3.10/site-packages/tiatoolbox/wsicore/wsireader.py:1940: UserWarning: Metadata: Falling back to TIFF resolution tag for microns-per-pixel (MPP).
  warnings.warn(
> |2023-07-04|13:49:41.062| [WARNING] /home/u2271662/.local/lib/python3.10/site-packages/tiatoolbox/wsicore/wsireader.py:1979: UserWarning: Metadata: Objective power inferred from microns-per-pixel (MPP).
  warnings.warn(

And it generates _5_ER_val.jpg_ in the _slide-thumbnails_ folder.

**Comment by measty** [comment]
Hi @Abdol,

By default the cli command when given a folder looks for these file types:
`@cli_file_type(default="*.ndpi, *.svs, *.mrxs, *.jp2")`
so try running your command with the added argument --file-types *.tiff, hopefully that will work.

**Comment by Abdol** [comment]
Thanks @measty! Yes, specifying the file type of WSIs worked. The command now looks like:

`tiatoolbox slide-thumbnail --img-input /path/to/folder/ --file-types *.tiff --output-path /path/to/slide-thumbnails`

One little quirk I found is that when I'm inside the WSI folder (as in I `cd` into `/path/to/folder/`) and run the command above, I get the following error:

> Usage: tiatoolbox slide-thumbnail [OPTIONS]
Try 'tiatoolbox slide-thumbnail -h' for help.
> Error: Got unexpected extra arguments (0_KI67_val.tiff 10_ER_val.tiff 10_HE_val.tiff 11_HE_val.tiff 11_KI67_val.tiff 12_ER_val.tiff 12_HE_val.tiff 13_HE_val.tiff 13_KI67_val.tiff _[THE REST OF THE FILES]_)

If I navigate outside the WSIs folder and run the command, it works fine. I'm not sure if this is a bug or natural behavior.

**Comment by shaneahmed** [comment]
As specifying file type works, I am closing this issue.
