### ISSUE TITLE
cannot import name 'Units' from 'tiatoolbox.wsicore.wsireader'

### ISSUE THREAD

**Issue by Czzh1** [TissueImageAnalytics/tiatoolbox#745]
- TIA Toolbox version: 1.4.1
- Python version: 3.8
- Operating System: windows

### What I Did

```
This is my code:
from tiatoolbox.wsicore.wsireader import (
    OpenSlideWSIReader,
    Resolution,
    WSIReader,
    Units,
)
and the pycharm told me there is no Units in  tiatoolbox.wsicore.wsireader (cannot import Units)
```

**Comment by Czzh1** [comment]
Anyone Know What's the problems ?

**Comment by measty** [comment]
Resolution and Units are in `tiatoolbox.typing`

```
from tiatoolbox.typing import Units, Resolution
```

**Comment by shaneahmed** [comment]
Are you using the same version of the toolbox? This was moved from wsireader to tiatoolbox.typing in the latest version.
