### ISSUE TITLE
Nucleus instance segmentation model output labels

### ISSUE THREAD

**Issue by deeplearningmaniac** [TissueImageAnalytics/tiatoolbox#750]
- TIA Toolbox version: 1.4.1
- Python version: 3.10.12
- Operating System: Debian 11

### Description

The nucleus instance segmentation models "hovernet_fast-pannuke", "hovernet_fast-monusac", etc produce type indexes 1, 2, 3, ..., for the nuclei they segment, but I've scoured the documentation and don't see any information on what types of cells these values correspond to. I've checked the dataset documentations and can see what the cell types are, but not which indexes map to which cell types. Is this documented anywhere?

**Comment by adamshephard** [comment]
Hi @deeplearningmaniac,

Thanks for raising this issue. We will aim to add further information on this to the readthedocs page.

For now, the labels are consistent with that used in the original HoVer-Net pipeline notebook: https://github.com/vqdang/hover_net/blob/master/examples/usage.ipynb

Best wishes,
Adam

**Comment by adamshephard** [comment]
We have addressed this in the following PR: https://github.com/TissueImageAnalytics/tiatoolbox/pull/751

**Comment by deeplearningmaniac** [comment]
> Hi @deeplearningmaniac,
> 
> Thanks for raising this issue. We will aim to add further information on this to the readthedocs page.
> 
> For now, the labels are consistent with that used in the original HoVer-Net pipeline notebook, where 0 is background: https://github.com/vqdang/hover_net/blob/master/examples/usage.ipynb
> 
> Best wishes, Adam

I'd just like to double check this -- in the [nucleus instance segmentation notebook](https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/examples/08-nucleus-instance-segmentation.ipynb), the color map used is 
```python
color_dict = {
    0: ("neoplastic epithelial", (255, 0, 0)),
    1: ("Inflammatory", (255, 255, 0)),
    2: ("Connective", (0, 255, 0)),
    3: ("Dead", (0, 0, 0)),
    4: ("non-neoplastic epithelial", (0, 0, 255)),
}
```
where 0 is "neoplastic epithelial" instead of "background". Is there a reason for this discrepancy? Should 0 be "background" or "neoplastic epithelial" (in the case of PanNuke)?

Thanks for the very quick replies!
