### ISSUE TITLE
Reading CZI files

### ISSUE THREAD

**Issue by KenAncheta** [TissueImageAnalytics/tiatoolbox#793]
- TIA Toolbox version: 1.5.1
- Python version: 3.11.8
- Operating System: MacOS Sonoma (14.3.1)

### Description

Trying to work on CZI files. I understand this is currently not supported, is there a work-around to import CZI using aicsimageio and just use TIAtoolbox downstream?

### What I Did

```
from tiatoolbox.wsicore.wsireader import OpenSlideWSIReader
# Load a WSI image
wsi = OpenSlideWSIReader.open(input_img="file.czi")
location = (0, 0)
size = (256, 256)
# Read a region at level 0 (baseline / full resolution)
img = wsi.read_rect(location, size)
# Read a region at 0.5 microns per pixel (mpp)
img = wsi.read_rect(location, size, 0.5, "mpp")
# This could also be written more verbosely as follows
img = wsi.read_rect(
    location,
    size,
    resolution=(0.5, 0.5),
    units="mpp",
)

Error:
FileNotSupportedError: File [/Users/ken/Desktop/376951](https://untitled+.vscode-resource.vscode-cdn.net/Users/ken/Desktop/376951);M1151;CANINE;AC-1.czi is not a supported file format.
```

**Comment by shaneahmed** [comment]
If you have a CZI reader in python, you can inherit `WSIReader` and customize read_bounds and read_rect functions. https://github.com/TissueImageAnalytics/tiatoolbox/blob/ffe9232181b60044fdf3c6bc32409ce357299e49/tiatoolbox/wsicore/wsireader.py#L208

We would welcome any contributions if in this case.
