### ISSUE TITLE
Tiatoolbox stopped working after generating yml file. SSL problem with openslide?

### ISSUE THREAD

**Issue by KenAncheta** [TissueImageAnalytics/tiatoolbox#803]
- TIA Toolbox version: 1.5.1
- Python version: 3.11.8
- Operating System: macOS Sonoma 14.4.1

### Description

I am trying to run the stain normalisation function from TIAToolbox. The functions were all running fine without any problem.  However, when I was generating yml file to run TIAToolbox on another machine, suddenly the environment and ipykernel containing the TIAToolbox disappeared. When I tried to reinstall the package from scratch using the installation guide (https://tia-toolbox.readthedocs.io/en/latest/installation.html), I can't run it anymore. 

### What I Did

```
So from scratch, I uninstalled homebrew and tiatoolbox.

$ conda create -n tiatoolbox python=3.11.8
$ conda activate tiatoolbox
(tiatoolbox) $ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" 
(tiatoolbox) $ brew install openjpeg openslide
(tiatoolbox) $ pip install tiatoolbox
(tiatoolbox) $ python -m ipykernel install --user --name tiatoolbox --display-name "TIAToolbox (3.11.8)"
(tiatoolbox) $ python
>>> import tiatoolbox
>>> from tiatoolbox.tools.stainnorm import MacenkoNormalizer
>>> Error (please see error below)

So I tried interacting with the environment using VSCode and use tiatoolbox as kernel:

import tiatoolbox
from tiatoolbox.tools.stainnorm import MacenkoNormalizer
Error (please see below)

I also tried installing homebrew from outside of the environment. Same thing occured. 

I can't seem to use tiatoolbox anymore.

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
OSError: dlopen(libopenslide.0.dylib, 0x0006): tried: 'libopenslide.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibopenslide.0.dylib' (no such file), '/Users/username/opt/anaconda3/envs/tia/lib/python3.11/lib-dynload/../../libopenslide.0.dylib' (no such file), '/Users/username/opt/anaconda3/envs/tia/bin/../lib/libopenslide.0.dylib' (no such file), '/usr/lib/libopenslide.0.dylib' (no such file, not in dyld cache), 'libopenslide.0.dylib' (no such file), '/usr/local/lib/libopenslide.0.dylib' (no such file), '/usr/lib/libopenslide.0.dylib' (no such file, not in dyld cache)

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
Cell In[6], [line 2](vscode-notebook-cell:?execution_count=6&line=2)
      [1](vscode-notebook-cell:?execution_count=6&line=1) import tiatoolbox
----> [2](vscode-notebook-cell:?execution_count=6&line=2) from tiatoolbox.tools.stainnorm import MacenkoNormalizer

ModuleNotFoundError: Couldn't locate OpenSlide dylib.  Is OpenSlide installed correctly?  https://openslide.org/api/python/#installing
```

**Comment by KenAncheta** [comment]
Hi @Abdol. Yes I am using Apple Silicon Mac. When I use  conda install -c conda-forge openslide, it gets stuck (code below). It's been 3 hours since I tried the installation using conda-forge.


conda install -c conda-forge openslide
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: / 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/osx-arm64::_ipyw_jlab_nb_ext_conf==0.1.0=py39hca03da5_1
  - defaults/osx-arm64::h5py==3.7.0=py39h7fe8675_0
  - defaults/osx-arm64::anaconda-navigator==2.3.2=py39hca03da5_0
  - defaults/osx-arm64::anaconda-client==1.11.0=py39hca03da5_0
  - defaults/osx-arm64::qtconsole==5.4.2=py39hca03da5_0
  - defaults/noarch::requests-file==1.5.1=pyhd3eb1b0_0
  - defaults/osx-arm64::statsmodels==0.13.2=py39h1a28f6b_0
  - defaults/osx-arm64::dask==2022.7.0=py39hca03da5_0
  - defaults/noarch::nbclassic==0.3.5=pyhd3eb1b0_0
  - defaults/osx-arm64::numpydoc==1.4.0=py39hca03da5_0
  - defaults/osx-arm64::scipy==1.9.1=py39h9d039d2_0
  - defaults/osx-arm64::nbconvert==6.4.4=py39hca03da5_0
  - defaults/osx-arm64::navigator-updater==0.3.0=py39hca03da5_0
  - defaults/osx-arm64::nbformat==5.5.0=py39hca03da5_0
  - defaults/osx-arm64::distributed==2022.7.0=py39hca03da5_0
  - defaults/osx-arm64::jupyter==1.0.0=py39hca03da5_8
  - defaults/osx-arm64::pyct==0.4.8=py39hca03da5_1
  - defaults/osx-arm64::twisted==22.2.0=py39h1a28f6b_1
  - defaults/osx-arm64::numpy==1.21.5=py39h42add53_3
  - defaults/osx-arm64::anaconda==2022.10=py39_0
  - defaults/osx-arm64::colorcet==3.0.0=py39hca03da5_0
  - defaults/osx-arm64::astropy==5.1=py39heec5a64_0
  - defaults/noarch::nltk==3.7=pyhd3eb1b0_0
  - defaults/osx-arm64::ipykernel==6.15.2=py39hca03da5_0
  - defaults/osx-arm64::widgetsnbextension==3.5.2=py39hca03da5_0
  - defaults/osx-arm64::terminado==0.13.1=py39hca03da5_0
  - defaults/osx-arm64::panel==0.13.1=py39hca03da5_0
  - defaults/osx-arm64::notebook==6.4.12=py39hca03da5_0
  - defaults/osx-arm64::ipython==8.4.0=py39hca03da5_0
  - defaults/osx-arm64::holoviews==1.15.0=py39hca03da5_0
  - defaults/noarch::conda-verify==3.4.2=py_1
  - defaults/osx-arm64::numexpr==2.8.3=py39h144ceef_0
  - defaults/noarch::jupyterlab_pygments==0.1.2=py_0
  - defaults/osx-arm64::conda==23.1.0=py39hca03da5_0
  - defaults/osx-arm64::conda-repo-cli==1.0.41=py39hca03da5_0
  - defaults/osx-arm64::anaconda-project==0.11.1=py39hca03da5_0
  - defaults/osx-arm64::bottleneck==1.3.5=py39heec5a64_0
  - defaults/noarch::intake==0.6.5=pyhd3eb1b0_0
  - defaults/osx-arm64::datashape==0.5.4=py39hca03da5_1
  - defaults/osx-arm64::matplotlib-inline==0.1.6=py39hca03da5_0
  - defaults/noarch::ipywidgets==7.6.5=pyhd3eb1b0_1
  - defaults/noarch::jupyter_console==6.4.3=pyhd3eb1b0_0
  - defaults/osx-arm64::nbclient==0.5.13=py39hca03da5_0
  - defaults/osx-arm64::datashader==0.14.1=py39hca03da5_0
  - defaults/noarch::seaborn==0.11.2=pyhd3eb1b0_0
  - defaults/osx-arm64::pywavelets==1.3.0=py39h1a28f6b_0
  - defaults/osx-arm64::pytest==7.1.2=py39hca03da5_0
  - defaults/osx-arm64::gensim==4.1.2=py39hc377ac9_0
  - defaults/noarch::automat==20.2.0=py_0
  - defaults/noarch::conda-token==0.4.0=pyhd3eb1b0_0
  - defaults/osx-arm64::hvplot==0.8.0=py39hca03da5_0
  - defaults/noarch::service_identity==18.1.0=pyhd3eb1b0_1
  - defaults/osx-arm64::matplotlib==3.5.2=py39hca03da5_0
  - defaults/osx-arm64::scrapy==2.6.2=py39hca03da5_0
  - defaults/osx-arm64::pytables==3.7.0=py39h701507b_0
  - defaults/osx-arm64::pyerfa==2.0.0=py39h1a28f6b_0
  - defaults/osx-arm64::patsy==0.5.2=py39hca03da5_1
  - defaults/osx-arm64::conda-build==3.22.0=py39hca03da5_0
  - defaults/noarch::tldextract==3.2.0=pyhd3eb1b0_0
  - defaults/noarch::xarray==0.20.1=pyhd3eb1b0_1
  - defaults/osx-arm64::bkcharts==0.2=py39hca03da5_1
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): | WARNING conda.models.version:get_matcher(546): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(546): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
done
Solving environment: / 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/osx-arm64::_ipyw_jlab_nb_ext_conf==0.1.0=py39hca03da5_1
  - defaults/osx-arm64::h5py==3.7.0=py39h7fe8675_0
  - defaults/osx-arm64::anaconda-navigator==2.3.2=py39hca03da5_0
  - defaults/osx-arm64::anaconda-client==1.11.0=py39hca03da5_0
  - defaults/osx-arm64::qtconsole==5.4.2=py39hca03da5_0
  - defaults/noarch::requests-file==1.5.1=pyhd3eb1b0_0
  - defaults/osx-arm64::statsmodels==0.13.2=py39h1a28f6b_0
  - defaults/osx-arm64::dask==2022.7.0=py39hca03da5_0
  - defaults/noarch::nbclassic==0.3.5=pyhd3eb1b0_0
  - defaults/osx-arm64::numpydoc==1.4.0=py39hca03da5_0
  - defaults/osx-arm64::scipy==1.9.1=py39h9d039d2_0
  - defaults/osx-arm64::nbconvert==6.4.4=py39hca03da5_0
  - defaults/osx-arm64::navigator-updater==0.3.0=py39hca03da5_0
  - defaults/osx-arm64::nbformat==5.5.0=py39hca03da5_0
  - defaults/osx-arm64::distributed==2022.7.0=py39hca03da5_0
  - defaults/osx-arm64::jupyter==1.0.0=py39hca03da5_8
  - defaults/osx-arm64::pyct==0.4.8=py39hca03da5_1
  - defaults/osx-arm64::twisted==22.2.0=py39h1a28f6b_1
  - defaults/osx-arm64::numpy==1.21.5=py39h42add53_3
  - defaults/osx-arm64::anaconda==2022.10=py39_0
  - defaults/osx-arm64::colorcet==3.0.0=py39hca03da5_0
  - defaults/osx-arm64::astropy==5.1=py39heec5a64_0
  - defaults/noarch::nltk==3.7=pyhd3eb1b0_0
  - defaults/osx-arm64::ipykernel==6.15.2=py39hca03da5_0
  - defaults/osx-arm64::widgetsnbextension==3.5.2=py39hca03da5_0
  - defaults/osx-arm64::terminado==0.13.1=py39hca03da5_0
  - defaults/osx-arm64::panel==0.13.1=py39hca03da5_0
  - defaults/osx-arm64::notebook==6.4.12=py39hca03da5_0
  - defaults/osx-arm64::ipython==8.4.0=py39hca03da5_0
  - defaults/osx-arm64::holoviews==1.15.0=py39hca03da5_0
  - defaults/noarch::conda-verify==3.4.2=py_1
  - defaults/osx-arm64::numexpr==2.8.3=py39h144ceef_0
  - defaults/noarch::jupyterlab_pygments==0.1.2=py_0
  - defaults/osx-arm64::conda==23.1.0=py39hca03da5_0
  - defaults/osx-arm64::conda-repo-cli==1.0.41=py39hca03da5_0
  - defaults/osx-arm64::anaconda-project==0.11.1=py39hca03da5_0
  - defaults/osx-arm64::bottleneck==1.3.5=py39heec5a64_0
  - defaults/noarch::intake==0.6.5=pyhd3eb1b0_0
  - defaults/osx-arm64::datashape==0.5.4=py39hca03da5_1
  - defaults/osx-arm64::matplotlib-inline==0.1.6=py39hca03da5_0
  - defaults/noarch::ipywidgets==7.6.5=pyhd3eb1b0_1
  - defaults/noarch::jupyter_console==6.4.3=pyhd3eb1b0_0
  - defaults/osx-arm64::nbclient==0.5.13=py39hca03da5_0
  - defaults/osx-arm64::datashader==0.14.1=py39hca03da5_0
  - defaults/noarch::seaborn==0.11.2=pyhd3eb1b0_0
  - defaults/osx-arm64::pywavelets==1.3.0=py39h1a28f6b_0
  - defaults/osx-arm64::pytest==7.1.2=py39hca03da5_0
  - defaults/osx-arm64::gensim==4.1.2=py39hc377ac9_0
  - defaults/noarch::automat==20.2.0=py_0
  - defaults/noarch::conda-token==0.4.0=pyhd3eb1b0_0
  - defaults/osx-arm64::hvplot==0.8.0=py39hca03da5_0
  - defaults/noarch::service_identity==18.1.0=pyhd3eb1b0_1
  - defaults/osx-arm64::matplotlib==3.5.2=py39hca03da5_0
  - defaults/osx-arm64::scrapy==2.6.2=py39hca03da5_0
  - defaults/osx-arm64::pytables==3.7.0=py39h701507b_0
  - defaults/osx-arm64::pyerfa==2.0.0=py39h1a28f6b_0
  - defaults/osx-arm64::patsy==0.5.2=py39hca03da5_1
  - defaults/osx-arm64::conda-build==3.22.0=py39hca03da5_0
  - defaults/noarch::tldextract==3.2.0=pyhd3eb1b0_0
  - defaults/noarch::xarray==0.20.1=pyhd3eb1b0_1
  - defaults/osx-arm64::bkcharts==0.2=py39hca03da5_1
-

**Comment by GeorgeBatch** [comment]
I think I had a similar issue on an M1 Mac. Updating conda through updating Miniconda distribution (https://docs.anaconda.com/free/miniconda/#quick-command-line-install) helped. I installed openslide and openjpeg as the very first thing after creating and activating the environment:

```shell
conda create -n tiatoolbox python=3.11 -y
conda activate tiatoolbox
conda install openslide openjpeg -c conda-forge
```

**Comment by KenAncheta** [comment]
@GeorgeBatch This solution worked for me! Thanks!
