### ISSUE TITLE
PanNuke TCGA-Slide List

### ISSUE THREAD

**Issue by FabianHoerst** [TissueImageAnalytics/tiatoolbox#808]
- TIA Toolbox version: All
- Python version: -
- Operating System: - 

#### Issue:

We are currently seeking information regarding the availability of a file list containing an overview of the TCGA data utilized in the creation of the PanNuke dataset. Our aim is to obtain a list of TCGA Slide-IDs that were specifically used in the PanNuke dataset creation process. This information is crucial for the scientific community as it will enable us to avoid any potential overlaps with other datasets and facilitate research in this area.

#### Request:

Could someone please assist in forwarding this inquiry to the appropriate individual that might have this information?

Thank you very much!

**Comment by shaneahmed** [comment]
@navidstuv @jgamper can you help with this?

**Comment by shaneahmed** [comment]
I have mentioned authors of the paper above. As this is not related to the toolbox, I am closing this issue. You can find the author list in the paper. https://warwick.ac.uk/fac/cross_fac/tia/data/pannuke
