### ISSUE TITLE
TIAToolbox cannot read all scenes of OME-TIFF that was originally a CZI

### ISSUE THREAD

**Issue by KenAncheta** [TissueImageAnalytics/tiatoolbox#834]
- TIA Toolbox version: 1.5.1
- Python version: 3.11.1
- Operating System: MacOS 14.5

### Description

This is a follow for this issue [(https://github.com/TissueImageAnalytics/tiatoolbox/issues/793)]

I want to load CZI using TIAToolbox. The solutions that were provided were to 1) inherit the WSIReader class to accommodate CZI and 2) convert CZI into TIAToolbox-supported formats. I am not much of a coder so I used the latter.

### What I Did

Used bftool's (7.3.0) bfconvert (https://downloads.openmicroscopy.org/bio-formats/7.3.0/artifacts/bftools.zip) to convert CZI into OME-TIFF file. 

`./bftools/bfconvert -noflat ./target_sample.czi ./target_sample_converted.ome.tiff`

To note, the original CZI file has 2 scenes (Fig. 1), the TIAtoolbox can only read 1 scene (Fig. 2), which is the second scene. Any workaround here?

```
import tiatoolbox
from tiatoolbox.wsicore.wsireader import WSIReader
from matplotlib import pyplot as plt

reader = WSIReader.open("target_sample_converted.ome.tiff")

thumbnail = reader.slide_thumbnail(resolution=20, units="power")
plt.imshow(thumbnail)
plt.axis("off")
plt.show()


location = (-500, 500)
size = (25000, 25000)
img = reader.read_rect(
    location,
    size,
    resolution=0.5,
    units="mpp",
)
plt.imshow(img)
plt.axis("off")
plt.show()
```

**Figure 1**
![Screenshot 2024-07-09 at 17 00 49](https://github.com/TissueImageAnalytics/tiatoolbox/assets/74475139/9b8542ba-5d74-4c8f-b586-50c1608aa1c1)

**Figure 2**
![Screenshot 2024-07-09 at 17 01 24](https://github.com/TissueImageAnalytics/tiatoolbox/assets/74475139/d3c6b3b8-3758-4415-814f-9cf0598f412a)

Although might be an entirely irrelevant issue, when bfconvert was applied when the newly generated OME-TIFF was read into QuPath (0.5.1 x64), the thumbnails (Fig. 1) looks correct but the image itself was mixed up (Fig. 3 and 4). Interestingly, TIAToolbox was seem to be able to read OME-TIFF without any problem aside from the scenes.

**Figure 3**
![Screenshot 2024-07-09 at 17 07 23](https://github.com/TissueImageAnalytics/tiatoolbox/assets/74475139/ff57a06d-99fa-47d9-94b3-acef78ea6467)

**Figure 4**
![Screenshot 2024-07-09 at 17 08 42](https://github.com/TissueImageAnalytics/tiatoolbox/assets/74475139/ac539345-c59a-4d57-8ea4-8a15b3d964b4)

**Comment by shaneahmed** [comment]
Can you share the czi/ome tiff file so we can check the issue in detail.

**Comment by shaneahmed** [comment]
Closing this issue as we cannot update without a sample image.
