### ISSUE TITLE
How to save images as TIFF files with metadata preserved

### ISSUE THREAD

**Issue by ziyuanzhao2000** [TissueImageAnalytics/tiatoolbox#839]
- TIA Toolbox version: 1.5.1
- Python version: 3.9
- Operating System: Linux

### Description
So I loaded a TIFF image with metadata using the `WSIReader` class and applied a color normalization method implemented by this toolbox, and then I want to save the image as a TIFF file. There doesn't seem to be a good way of doing this? I found `utils.misc.imwrite()` but it doesn't retain the metadata fields in the images that I loaded. Please let me know how should I deal with this. Thanks!

**Comment by mostafajahanifar** [comment]
Hi,

Thanks for raising this issue. Unfortunately, we do not support writing WSIs into TIFF. However, you should be able to easily do that using TIFFFile library (or other similar libraries):
https://github.com/cgohlke/tifffile/
