### ISSUE TITLE
KeyError unset_removal_flag function (line 430) in NucleusInstanceSegmentor

### ISSUE THREAD

**Issue by FraukeWilm** [TissueImageAnalytics/tiatoolbox#840]
- TIA Toolbox version: 1.3.0
- Python version: 3.9
- Operating System: macOS

Hi guys,

I wanted to use HoverNet for a simple nucleus segmentation on a WSI. I followed your demo [here](https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/examples/08-nucleus-instance-segmentation.ipynb) and encountered a key error when extracting the tile info (before prediction). The key error occurred in line 430 of the NucleusInstanceSegmentor and I could not figure out the problem. 

```
model = NucleusInstanceSegmentor(
            pretrained_model="hovernet_fast-pannuke",
            num_loader_workers=0,
            num_postproc_workers=0,
            batch_size=8,
            auto_generate_mask=False,
            verbose=False,
        )
wsi_output = model.predict(
            [filename],
            masks=None,
            save_dir="tmp/",
            mode="wsi",
            on_gpu=False,
            crash_on_exception=True,
        )
```

_ERROR_
```
Traceback (most recent call last):
  File ".venv/lib/python3.9/site-packages/tiatoolbox/models/engine/nucleus_instance_segmentor.py", line 444, in _get_tile_info
    flag = unset_removal_flag(boxes, flag)
  File ".venv/lib/python3.9/site-packages/tiatoolbox/models/engine/nucleus_instance_segmentor.py", line 429, in unset_removal_flag
    sel_indices = [
  File ".venv/lib/python3.9/site-packages/tiatoolbox/models/engine/nucleus_instance_segmentor.py", line 430, in <listcomp>
    index_by_id[id(geo)] for geo in spatial_indexer.query(sel_box)
KeyError: 12601831632
```

The index_by_id dict was non-empty with 825 entries, but the requested key did not exist. I hope you can help me to resolve this issue.

Best,
Frauke

**Comment by measty** [comment]
Hi @FraukeWilm 

This is caused by a mismatch between your tiatoolbox version, and the version of shapely library in your environment. To fix it, you will likely need to either update to the most recent tiatoolbox (1.5.1), or if you want to continue using tiatoolbox 1.3 for now, instead downgrade your shapely version to <2.0.

Hope that helps!
Mark

**Comment by FraukeWilm** [comment]
Hi Mark,

Jup, upgrading to version 1.5.1 solved the issue. Thanks for the quick reply!


Best,
Frauke
