### ISSUE TITLE
fcn_resnet50_unet-bcss.pth model not available (connection refused)

### ISSUE THREAD

**Issue by uladzislauivanou** [TissueImageAnalytics/tiatoolbox#858]
- tiatoolbox 1.3.3:
- Python 3.10:
- Ubuntu 20.04:

### Description

Model not available:

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='tiatoolbox.dcs.warwick.ac.uk', port=443): Max retries exceeded with url: /models/seg/fcn_resnet50_unet-bcss.pth (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7edd52d69c30>: Failed to establish a new connection: [Errno 111] Connection refused'))

### What I Did

Just running semantic segmentor as before, nothing really changed in a setup it just stopped receiving responses for this mode

        self.histomorpho_segmentor = SemanticSegmentor(
            pretrained_model="fcn_resnet50_unet-bcss",
            auto_generate_mask=True,
        )
        
        
  Tissue segmentation works fine

**Comment by shaneahmed** [comment]
We are upgrading our servers. The servers will have intermittent connection over next few weeks.

**Comment by fastorik** [comment]
> We are upgrading our servers. The servers will have intermittent connection over next few weeks.

Thanks! Appreciate
