### ISSUE TITLE
Warwick URLs refusing connection for sample downloads in Semantic Segmentation Notebook

### ISSUE THREAD

**Issue by mhwilder** [TissueImageAnalytics/tiatoolbox#859]
The download step in the [Semantic Segmentation notebook](https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/examples/06-semantic-segmentation.ipynb) does not appear to be working. It produces the following error:

`(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1055da550>: Failed to establish a new connection: [Errno 61] Connection refused'))`

When I tried to download the files elsewhere, I was still getting the same error. Perhaps settings on the server have changed or maybe it's just down. I'm mainly trying to get the following file:

https://tiatoolbox.dcs.warwick.ac.uk//models/seg/fcn-tissue_mask.pth

Is it available elsewhere?

**Comment by shaneahmed** [comment]
We are in the process of upgrading our servers. The connection will be intermittent until end of Sep.
