### ISSUE TITLE
resnet18-idars-tumour.pth model not available

### ISSUE THREAD

**Issue by 24hourssss** [TissueImageAnalytics/tiatoolbox#860]
- TIA Toolbox version:1.3.3
- Python version:3.10
- Operating System:colab

### Description

ConnectionError: HTTPSConnectionPool(host='tiatoolbox.dcs.warwick.ac.uk', port=443): Max retries exceeded with url: /models/idars/resnet18-idars-tumour.pth (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9d82fb9b10>: Failed to establish a new connection: [Errno 111] Connection refused'))

### What I Did

When I was running this block

```
tumour_predictor = PatchPredictor(
    pretrained_model="resnet18-idars-tumour",
    batch_size=64,
    num_loader_workers=WORKERS,
)
```

**Comment by shaneahmed** [comment]
We are in the process of upgrading our servers. The connection will be intermittent until end of Sep.
